### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by augmen** [facebookresearch/DrQA#113]
after running 

`python3 scripts/pipeline/interactive.py`
or 
`sudo python3 scripts/pipeline/interactive.py`

got this error 

`FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.5/dist-packages/drqa-0.1.0-py3.5.egg/data/wikipedia/docs-tfidf-ngram=2-hash=16777216-tokenizer=simple.npz'`

more details 

> `04/16/2018 08:47:33 AM: [ Running on CPU only. ]
04/16/2018 08:47:33 AM: [ Initializing model... ]
04/16/2018 08:47:33 AM: [ Loading model /usr/local/lib/python3.5/dist-packages/drqa-0.1.0-py3.5.egg/data/reader/single.mdl ]
Traceback (most recent call last):
  File "scripts/reader/interactive.py", line 53, in <module>
    normalize=not args.no_normalize)
  File "/usr/local/lib/python3.5/dist-packages/drqa-0.1.0-py3.5.egg/drqa/reader/predictor.py", line 61, in __init__
    normalize=normalize)
  File "/usr/local/lib/python3.5/dist-packages/drqa-0.1.0-py3.5.egg/drqa/reader/model.py", line 428, in load
    filename, map_location=lambda storage, loc: storage
  File "/home/swap/.local/lib/python3.5/site-packages/torch/serialization.py", line 265, in load
    f = open(f, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.5/dist-packages/drqa-0.1.0-py3.5.egg/data/reader/single.mdl'`

Shall i install the python into virtual env ?

got the same error with 👍 

`sudo python3 ~/DrQA/scripts/reader/interactive.py  `

**Comment by ajfisch** [comment]
Have you downloaded the models?

**Comment by augmen** [comment]
Yes resolved the errors . please close it .
