### ISSUE TITLE
Error in Interactive session

### ISSUE THREAD

**Issue by augmen** [facebookresearch/DrQA#116]
after running the `python3 scripts/pipeline/interactive.py` i got this error 

`Traceback (most recent call last):
  File "scripts/pipeline/interactive.py", line 16, in <module>
    from drqa import pipeline
ImportError: No module named 'drqa'`

After copy and paste the entire interactive.py file in python3 console the interactive session to start. Then i type the Questions as 👍 

> process('What is the answer to life, the universe, and everything?')
I got this error

`File "/usr/lib/python3.5/code.py", line 91, in runcode
    exec(code, self.locals)
  File "<console>", line 1, in <module>
  File "<stdin>", line 2, in process
NameError: name 'DrQA' is not defined`

Please guide

I am currently using Linux 4GB ram machine. Any guidance would it be sufficient for the DrQA ?

With 8GB ram and 4CPU cores. i got this error
`Traceback (most recent call last):
  File "<stdin>", line 7, in <module>
  File "/root/DrQA/drqa/pipeline/drqa.py", line 109, in __init__
    self.ranker = ranker_class(**ranker_opts)
  File "/root/DrQA/drqa/retriever/tfidf_doc_ranker.py", line 37, in __init__
    matrix, metadata = utils.load_sparse_csr(tfidf_path)
  File "/root/DrQA/drqa/retriever/utils.py", line 34, in load_sparse_csr
    matrix = sp.csr_matrix((loader['data'], loader['indices'],
  File "/root/pt/local/lib/python3.5/site-packages/numpy/lib/npyio.py", line 235, in __getitem__
    pickle_kwargs=self.pickle_kwargs)
  File "/root/pt/local/lib/python3.5/site-packages/numpy/lib/format.py", line 674, in read_array
    array = numpy.ndarray(count, dtype=dtype)
MemoryError
`

I don't no why numpy gove me error ?

**Comment by ajfisch** [comment]
Please see the readme on how to run `setup.py` and setup your development environment. The readme also gives guidelines on resource requirements, 8GB of RAM is not enough to run the full Wikipedia queries.
