### ISSUE TITLE
TypeError: invalid types when training

### ISSUE THREAD

**Issue by jplu** [facebookresearch/DrQA#135]
Hello,
I get the following error when I train my reader:
```
05/07/2018 11:27:18 AM: [ ---------------------------------------------------------------------------------------------------- ]
05/07/2018 11:27:18 AM: [ Starting training... ]
/home/jplu/DrQA/drqa/reader/layers.py:209: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  alpha_flat = F.softmax(scores.view(-1, y.size(1)))
/home/jplu/DrQA/drqa/reader/layers.py:280: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  alpha = F.softmax(scores)
/home/jplu/DrQA/drqa/reader/layers.py:250: UserWarning: Implicit dimension choice for log_softmax has been deprecated. Change the call to include dim=X as an argument.
  alpha = F.log_softmax(xWy)
/home/jplu/DrQA/drqa/reader/model.py:226: UserWarning: torch.nn.utils.clip_grad_norm is now deprecated in favor of torch.nn.utils.clip_grad_norm_.
  self.args.grad_clipping)
/home/jplu/DrQA/drqa/reader/model.py:235: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  return loss.data[0], ex[0].size(0)
05/07/2018 11:27:18 AM: [ train: Epoch = 0 | iter = 0/1 | loss = 8.96 | elapsed time = 0.35 (s) ]
05/07/2018 11:27:18 AM: [ train: Epoch 0 done. Time for epoch = 0.35 (s) ]
/home/jplu/DrQA/drqa/reader/model.py:281: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
  for e in ex[:5]]
/home/jplu/DrQA/drqa/reader/layers.py:253: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  alpha = F.softmax(xWy)
Traceback (most recent call last):
  File "scripts/reader/train.py", line 542, in <module>
    main(args)
  File "scripts/reader/train.py", line 484, in main
    validate_unofficial(args, train_loader, model, stats, mode='train')
  File "scripts/reader/train.py", line 256, in validate_unofficial
    accuracies = eval_accuracies(pred_s, target_s, pred_e, target_e)
  File "scripts/reader/train.py", line 345, in eval_accuracies
    if any([1 for _s, _e in zip(target_s[i], target_e[i])
  File "scripts/reader/train.py", line 346, in <listcomp>
    if _s == pred_s[i] and _e == pred_e[i]]):
TypeError: eq() received an invalid combination of arguments - got (numpy.ndarray), but expected one of:
 * (Tensor other)
      didn't match because some of the arguments have invalid types: (numpy.ndarray)
 * (float other)
      didn't match because some of the arguments have invalid types: (numpy.ndarray)
```

I suspect to have a wrong version for one of the used Python lib. Here the command line I used for training:
```
python scripts/reader/train.py --embedding-file cc.en.300.vec --tune-partial 1000 --model-name en-model --train-file train-en-processed-adel.txt --dev-file dev-en-processed-adel.txt --dev-json dev-en.json --uncased-question True --uncased-doc True
```

Here the version of each required Python lib:
```
numpy==1.13.3
scikit-learn==0.19.1
termcolor==1.1.0
regex==2017.4.5
tqdm==4.19.4
prettytable==0.7.2
scipy==1.0.0
nltk==3.2.5
pexpect==4.5.0
torch==0.4.0
torchvision==0.2.1
```

Other info
* commit: 36a6e3f493ac1668d6b16d9d2169524be714bc81
* Python 3.6.3
* OS: Debian Testing

Thanks in advance for any help!

**Comment by jplu** [comment]
I did update to the last commit (d4228899a9c963c7c54ae9616ac1c4496d5499ab) and I still have the same error.

**Comment by jplu** [comment]
I did update the outdated Python lib to the following version:
```
numpy==1.14.3
regex==2018.2.21
tqdm==4.19.4
scipy==1.1.0
nltk==3.3
```
And it doesn't change anything :(

**Comment by ajfisch** [comment]
pytorch `0.4.0` is not supported yet, see #128

**Comment by jplu** [comment]
Ah! Thanks!! I think would be nice to specify this in the README :)
