### ISSUE TITLE
Error in preprocess.py

### ISSUE THREAD

**Issue by shubham15098** [facebookresearch/DrQA#140]
from drqa import tokenizers
tok = tokenizers.CoreNLPTokenizer()

These commands are working fine on terminal. But still I am getting this error :-

`File "/home/allmin/.conda/envs/my_env/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)

During handling of the above exception, another exception occurred:

  File "/home/allmin/.conda/envs/my_env/lib/python3.6/multiprocessing/pool.py", line 103, in worke
r
    initializer(*initargs)
  File "scripts/reader/preprocess.py", line 36, in init
    TOK = tokenizer_class(**options)
  File "/home/philips/Disk2/shubzz/facebookPytorch/DrQA/drqa/tokenizers/corenlp_tokenizer.py", lin
e 33, in __init__
    self._launch()
  File "/home/philips/Disk2/shubzz/facebookPytorch/DrQA/drqa/tokenizers/corenlp_tokenizer.py", lin
e 61, in _launch
    self.corenlp.expect_exact('NLP>', searchwindowsize=100)
Traceback (most recent call last):
  File "/home/allmin/.conda/envs/my_env/lib/python3.6/site-packages/pexpect/spawnbase.py", line 39
0, in expect_exact
    return exp.expect_loop(timeout)
  File "/home/allmin/.conda/envs/my_env/lib/python3.6/site-packages/pexpect/expect.py", line 107,
in expect_loop
`

Can anyone help?

**Comment by ajfisch** [comment]
There are many resolved issues on this. Have you checked them?

**Comment by shubham15098** [comment]
Yes, I guess. They mainly said to check whether java 8 is  installed properly or have you installed the CoreNlpTokenizer. But I think both of them are working in my case. I have checked it using these commands:-
from drqa import tokenizers
tok = tokenizers.CoreNLPTokenizer()

and they were running fine.

**Comment by BarclayII** [comment]
I reduced the number of workers and it worked well.
