### ISSUE TITLE
other tokenizers are not working,

### ISSUE THREAD

**Issue by tiru1930** [facebookresearch/DrQA#15]
with spacy 

spacy tokenizer is is not imported some lib error 

with simple and regxp , below error is coming 
Traceback (most recent call last):
  File "/usr/lib/python3.5/code.py", line 91, in runcode
    exec(code, self.locals)
  File "<console>", line 1, in <module>
  File "scripts/reader/interactive.py", line 62, in process
    predictions = predictor.predict(document, question, candidates, top_n)
  File "/usr/local/lib/python3.5/dist-packages/drqa-0.1.0-py3.5.egg/drqa/reader/predictor.py", line 86, in predict
    results = self.predict_batch([(document, question, candidates,)], top_n)
  File "/usr/local/lib/python3.5/dist-packages/drqa-0.1.0-py3.5.egg/drqa/reader/predictor.py", line 126, in predict_batch
    batch_exs = batchify([vectorize(e, self.model) for e in examples])
  File "/usr/local/lib/python3.5/dist-packages/drqa-0.1.0-py3.5.egg/drqa/reader/predictor.py", line 126, in <listcomp>
    batch_exs = batchify([vectorize(e, self.model) for e in examples])
  File "/usr/local/lib/python3.5/dist-packages/drqa-0.1.0-py3.5.egg/drqa/reader/vector.py", line 33, in vectorize
    q_lemma = {w for w in ex['qlemma']} if args.use_lemma else None
TypeError: 'NoneType' object is not iterable

**Comment by ajfisch** [comment]
The default model uses extra annotations (part of speech tagging, lemmatization, named entity recognition) for extra features to the document encoding. The simple and regexp tokenizers only tokenize.

You should have had a warning at startup that said: `RegexpTokenizer only tokenizes! Skipping annotators: {'lemma', 'pos', 'ner'}`.

In the [README installation](https://github.com/facebookresearch/DrQA#installing-drqa) section I explain:
> Note: requirements.txt includes a subset of all the possible required packages. Depending on what you want to run, you might need to install an extra package (e.g. spacy).
>
> If you use the CoreNLPTokenizer or SpacyTokenizer you also need to download the Stanford CoreNLP jars and spaCy en model, respectively.

To download and use spacy, run:
`pip install spacy && python -m spacy download en`
