### ISSUE TITLE
No module named 'drqa'

### ISSUE THREAD

**Issue by antoinecomp** [facebookresearch/DrQA#160]
I tried to run `python3.6 scripts/pipeline/interactive.py` to drop into an interactive session but it seems that anywhere I try it I have this `No module named 'drqa'` error:

```
mike@mike-thinks:~/Programing/DrQA$ python3.6 scripts/pipeline/interactive.py
Traceback (most recent call last):
  File "scripts/pipeline/interactive.py", line 16, in <module>
    from drqa import pipeline
ModuleNotFoundError: No module named 'drqa'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 63, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
  File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
    from apport.report import Report
  File "/usr/lib/python3/dist-packages/apport/report.py", line 30, in <module>
    import apport.fileutils
  File "/usr/lib/python3/dist-packages/apport/fileutils.py", line 23, in <module>
    from apport.packaging_impl import impl as packaging
  File "/usr/lib/python3/dist-packages/apport/packaging_impl.py", line 23, in <module>
    import apt
  File "/usr/lib/python3/dist-packages/apt/__init__.py", line 23, in <module>
    import apt_pkg
ModuleNotFoundError: No module named 'apt_pkg'

Original exception was:
Traceback (most recent call last):
  File "scripts/pipeline/interactive.py", line 16, in <module>
    from drqa import pipeline
ModuleNotFoundError: No module named 'drqa'
```

I don't know if this is related but I had the following weird output when downloading all provided trained models and data for Wikipedia question answering :

```
mike@mike-thinks:~/Programing/DrQA$ ./download.sh
DRQA_DATA not set; downloading to default path ('data').
--2018-07-10 09:57:12--  https://s3.amazonaws.com/fair-data/drqa/data.tar.gz
Resolving s3.amazonaws.com (s3.amazonaws.com)... 52.216.128.37
Connecting to s3.amazonaws.com (s3.amazonaws.com)|52.216.128.37|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 8104538193 (7,5G) [application/x-gzip]
Saving to: ‘./data.tar.gz’

./data.tar.gz                             80%[================================================================>                ]   6,06G  1,13MB/s    in 39m 22s 

Cannot write to ‘./data.tar.gz’ (Success).
```

**Comment by ajfisch** [comment]
Did you run setup.py like it says in the README?

**Comment by antoinecomp** [comment]
Yes, I did `python setup.py develop` and the output seemed to be good.
On es.stackoverflow.com on m'a dit que la raison pourrait être que I run the module as a main script and I can not use relative imports like you would in a package. The solution is to add the path of my parent directory to the PYTHONPATH in `interactive.py:`

```
import inspect
import sys
import os

current = os.path.dirname(os.path.abspath(inspect.getfile(inspect.currentframe())))
sys.path.append(os.path.join(os.path.dirname(__file__), "../.."))
```

For information the output of `python setup.py develop` is [here](http://freetexthost.com/qja4vs1afv)

**Comment by ajfisch** [comment]
What is in your python path by default?

import sys; print(sys.path)

 Normally the setup.py script should put drqa into your python path for the future.

**Comment by antoinecomp** [comment]
@ajfisch Here it is:
```
>>> import sys; print(sys.path)
['', '/usr/lib/python36.zip', '/usr/lib/python3.6', '/usr/lib/python3.6/lib-dynload', '/home/mike/.local/lib/python3.6/site-packages', '/usr/local/lib/python3.6/dist-packages', '/usr/lib/python3/dist-packages']

```

**Comment by antoinecomp** [comment]
reinstalled the requirements and the setup with a new environment and it solved the issue
