### ISSUE TITLE
Missing data while downloading ? No such file or directory docs-tfidf-ngram=2-hash=16777216-tokenizer=simple.npz

### ISSUE THREAD

**Issue by antoinecomp** [facebookresearch/DrQA#161]
I have some issues when trying to drop into the interactive session. It seems that I'm missing files in the data directory. I'm redownloading it at the moment but as far as it takes time I'm wondering meanwhile if it can be for another reason. Here is the error:

```
(drqa_env) mike@mike-thinks:~/Programing/DrQA$ python scripts/pipeline/interactive.py
07/16/2018 11:32:41 AM: [ Running on CPU only. ]
07/16/2018 11:32:41 AM: [ Initializing pipeline... ]
07/16/2018 11:32:41 AM: [ Initializing document ranker... ]
07/16/2018 11:32:41 AM: [ Loading /home/mike/Programing/DrQA/data/wikipedia/docs-tfidf-ngram=2-hash=16777216-tokenizer=simple.npz ]
Traceback (most recent call last):
  File "scripts/pipeline/interactive.py", line 83, in <module>
    tokenizer=args.tokenizer
  File "/home/mike/Programing/DrQA/drqa/pipeline/drqa.py", line 109, in __init__
    self.ranker = ranker_class(**ranker_opts)
  File "/home/mike/Programing/DrQA/drqa/retriever/tfidf_doc_ranker.py", line 37, in __init__
    matrix, metadata = utils.load_sparse_csr(tfidf_path)
  File "/home/mike/Programing/DrQA/drqa/retriever/utils.py", line 33, in load_sparse_csr
    loader = np.load(filename)
  File "/home/mike/Programing/drqa_env/lib/python3.6/site-packages/numpy/lib/npyio.py", line 372, in load
    fid = open(file, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/home/mike/Programing/DrQA/data/wikipedia/docs-tfidf-ngram=2-hash=16777216-tokenizer=simple.npz'
```

I had the following weird output when downloading all provided trained models and data for Wikipedia question answering :

```
mike@mike-thinks:~/Programing/DrQA$ ./download.sh
DRQA_DATA not set; downloading to default path ('data').
--2018-07-10 09:57:12--  https://s3.amazonaws.com/fair-data/drqa/data.tar.gz
Resolving s3.amazonaws.com (s3.amazonaws.com)... 52.216.128.37
Connecting to s3.amazonaws.com (s3.amazonaws.com)|52.216.128.37|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 8104538193 (7,5G) [application/x-gzip]
Saving to: ‘./data.tar.gz’

./data.tar.gz                             80%[================================================================>                ]   6,06G  1,13MB/s    in 39m 22s 

Cannot write to ‘./data.tar.gz’ (Success).
```

I tried to download it again and now got the following error: 

```
(drqa_env) mike@mike-thinks:~/Programing/DrQA$ python scripts/pipeline/interactive.py
07/16/2018 07:49:47 PM: [ Running on CPU only. ]
07/16/2018 07:49:47 PM: [ Initializing pipeline... ]
07/16/2018 07:49:47 PM: [ Initializing document ranker... ]
07/16/2018 07:49:47 PM: [ Loading /home/mike/Programing/DrQA/data/wikipedia/docs-tfidf-ngram=2-hash=16777216-tokenizer=simple.npz ]
Traceback (most recent call last):
  File "scripts/pipeline/interactive.py", line 83, in <module>
    tokenizer=args.tokenizer
  File "/home/mike/Programing/DrQA/drqa/pipeline/drqa.py", line 109, in __init__
    self.ranker = ranker_class(**ranker_opts)
  File "/home/mike/Programing/DrQA/drqa/retriever/tfidf_doc_ranker.py", line 37, in __init__
    matrix, metadata = utils.load_sparse_csr(tfidf_path)
  File "/home/mike/Programing/DrQA/drqa/retriever/utils.py", line 33, in load_sparse_csr
    loader = np.load(filename)
  File "/home/mike/Programing/drqa_env/lib/python3.6/site-packages/numpy/lib/npyio.py", line 414, in load
    pickle_kwargs=pickle_kwargs)
  File "/home/mike/Programing/drqa_env/lib/python3.6/site-packages/numpy/lib/npyio.py", line 173, in __init__
    _zip = zipfile_factory(fid)
  File "/home/mike/Programing/drqa_env/lib/python3.6/site-packages/numpy/lib/npyio.py", line 103, in zipfile_factory
    return zipfile.ZipFile(file, *args, **kwargs)
  File "/usr/lib/python3.6/zipfile.py", line 1108, in __init__
    self._RealGetContents()
  File "/usr/lib/python3.6/zipfile.py", line 1175, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
Exception ignored in: <bound method NpzFile.__del__ of <numpy.lib.npyio.NpzFile object at 0x7f146d7209e8>>
Traceback (most recent call last):
  File "/home/mike/Programing/drqa_env/lib/python3.6/site-packages/numpy/lib/npyio.py", line 210, in __del__
    self.close()
  File "/home/mike/Programing/drqa_env/lib/python3.6/site-packages/numpy/lib/npyio.py", line 201, in close
    if self.zip is not None:
AttributeError: 'NpzFile' object has no attribute 'zip'
```

The downloading went to full 100% but it seems taht it struggled for it

```
2018-07-16 15:57:08 (328 KB/s) - Read error at byte 6036771385/8104538193 (Connection reset by peer). Retrying.

--2018-07-16 15:57:11--  (try: 4)  https://s3.amazonaws.com/fair-data/drqa/data.tar.gz
Connecting to s3.amazonaws.com (s3.amazonaws.com)|52.216.98.165|:443... connected.
HTTP request sent, awaiting response... 206 Partial Content
Length: 8104538193 (7,5G), 2067766808 (1,9G) remaining [application/x-gzip]
Saving to: ‘./data.tar.gz’

./data.tar.gz        95%[++++++++++++++====> ]   7,21G  42,2KB/s    in 1h 46m  

2018-07-16 17:49:12 (260 KB/s) - Read error at byte 7743190141/8104538193 (Connection reset by peer). Retrying.

--2018-07-16 17:49:16--  (try: 5)  https://s3.amazonaws.com/fair-data/drqa/data.tar.gz
Connecting to s3.amazonaws.com (s3.amazonaws.com)|52.216.98.165|:443... connected.
HTTP request sent, awaiting response... 206 Partial Content
Length: 8104538193 (7,5G), 361348052 (345M) remaining [application/x-gzip]
Saving to: ‘./data.tar.gz’

./data.tar.gz       100%[+++++++++++++++++++>]   7,55G   315KB/s    in 16m 23s 

2018-07-16 18:05:39 (359 KB/s) - ‘./data.tar.gz’ saved [8104538193/8104538193]

data/
data/datasets/
data/datasets/CuratedTrec-test.txt
data/datasets/CuratedTrec-train.txt
data/datasets/WikiMovies-entities.txt
data/datasets/WikiMovies-test.txt
data/datasets/WikiMovies-train.txt
data/reader/
data/reader/multitask.mdl
data/reader/single.mdl
data/wikipedia/
data/wikipedia/docs-tfidf-ngram=2-hash=16777216-tokenizer=simple.npz
tar: data/wikipedia/docs-tfidf-ngram=2-hash=16777216-tokenizer=simple.npz: Wrote only 8192 of 10240 bytes
data/wikipedia/docs.db
tar: data/wikipedia/docs.db: Wrote only 5632 of 10240 bytes
tar: Exiting with failure status due to previous errors

```

**Comment by antoinecomp** [comment]
Yes, did it, think it worked
