### ISSUE TITLE
Memory error from NumPy while calling for reader model

### ISSUE THREAD

**Issue by antoinecomp** [facebookresearch/DrQA#162]
Hi, I tried to run the `interactive.py` but after asking my first question to the prompt it seems that it runs short of RAM memory while calling for the reader model.

```
(wiki_env) mike@mike-thinks:~/Programing/WikiQueri/DrQA$ python3.6 scripts/pipeline/interactive.py 
07/19/2018 01:49:54 PM: [ Running on CPU only. ]
07/19/2018 01:49:54 PM: [ Initializing pipeline... ]
07/19/2018 01:49:54 PM: [ Initializing document ranker... ]
07/19/2018 01:49:54 PM: [ Loading /home/mike/Programing/WikiQueri/DrQA/data/wikipedia/docs-tfidf-ngram=2-hash=16777216-tokenizer=simple.npz ]
Traceback (most recent call last):
  File "scripts/pipeline/interactive.py", line 69, in <module>
    reader_model=args.reader_model,
  File "/home/mike/Programing/WikiQueri/DrQA/drqa/pipeline/drqa.py", line 109, in __init__
    self.ranker = ranker_class(**ranker_opts)
  File "/home/mike/Programing/WikiQueri/DrQA/drqa/retriever/tfidf_doc_ranker.py", line 37, in __init__
    matrix, metadata = utils.load_sparse_csr(tfidf_path)
  File "/home/mike/Programing/WikiQueri/DrQA/drqa/retriever/utils.py", line 34, in load_sparse_csr
    matrix = sp.csr_matrix((loader['data'], loader['indices'],
  File "/home/mike/.local/lib/python3.6/site-packages/numpy/lib/npyio.py", line 235, in __getitem__
    pickle_kwargs=self.pickle_kwargs)
  File "/home/mike/.local/lib/python3.6/site-packages/numpy/lib/format.py", line 674, in read_array
    array = numpy.ndarray(count, dtype=dtype)
MemoryError
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 63, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
  File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
    from apport.report import Report
  File "/usr/lib/python3/dist-packages/apport/report.py", line 30, in <module>
    import apport.fileutils
  File "/usr/lib/python3/dist-packages/apport/fileutils.py", line 23, in <module>
    from apport.packaging_impl import impl as packaging
  File "/usr/lib/python3/dist-packages/apport/packaging_impl.py", line 23, in <module>
    import apt
  File "/usr/lib/python3/dist-packages/apt/__init__.py", line 23, in <module>
    import apt_pkg
ModuleNotFoundError: No module named 'apt_pkg'

Original exception was:
Traceback (most recent call last):
  File "scripts/pipeline/interactive.py", line 69, in <module>
    reader_model=args.reader_model,
  File "/home/mike/Programing/WikiQueri/DrQA/drqa/pipeline/drqa.py", line 109, in __init__
    self.ranker = ranker_class(**ranker_opts)
  File "/home/mike/Programing/WikiQueri/DrQA/drqa/retriever/tfidf_doc_ranker.py", line 37, in __init__
    matrix, metadata = utils.load_sparse_csr(tfidf_path)
  File "/home/mike/Programing/WikiQueri/DrQA/drqa/retriever/utils.py", line 34, in load_sparse_csr
    matrix = sp.csr_matrix((loader['data'], loader['indices'],
  File "/home/mike/.local/lib/python3.6/site-packages/numpy/lib/npyio.py", line 235, in __getitem__
    pickle_kwargs=self.pickle_kwargs)
  File "/home/mike/.local/lib/python3.6/site-packages/numpy/lib/format.py", line 674, in read_array
    array = numpy.ndarray(count, dtype=dtype)
MemoryError
```

**Comment by antoinecomp** [comment]
@ajfisch , not sure about it but here is the output of `free -m` it's an Inspiron 3000 series with a dual boot Linux/Windows 10

```
              total        used        free      shared  buff/cache   available
Mem:           7888        5515        1013         320        1359        1718
Swap:             0           0           0
```

**Comment by binjiaqm** [comment]
Same issue with 16GB.

**Comment by antoinecomp** [comment]
@binjiaqm This is interesting then. You should check [DeepPavlov](https://deeppavlov.ai/deeppavlov/skills/odqa/), a DrQA equivalent whose ranker is based on DrQa which warned that 16 GB of RAM was required.

I do not know more

**Comment by binjiaqm** [comment]
@antoinecomp  Good to know. Thanks.

**Comment by ajfisch** [comment]
You need around 15GB of RAM (with sufficient swap) to run the full Wikipedia models.
