### ISSUE TITLE
trying to convert multitask.mdl to ONNX

### ISSUE THREAD

**Issue by dhruvsus** [facebookresearch/DrQA#165]
Hi, I'm trying to convert the multitask.mdl model to ONNX. I created a DocReader object using the DocReader.load() method. Then, I tried to use torch.onnx._export(model, x, "drqa_multitask.onnx", export_params=True), but it fails. I tried to do the same with the DocReader.network attribute, assuming it would work because it inherits from nn.Module. 
#input to the model
x=[]
x.append(torch.randn(1,32,requires_grad=True))
x.append(torch.randn(1,32,3,requires_grad=True))
x.append(torch.randn(1,32,requires_grad=True))
x.append(torch.randn(1,5,requires_grad=True))
x.append(torch.randn(1,5,requires_grad=True))

I got the dimensions from running the model with one document, and print the *inputs in network(*inputs)
Traceback (most recent call last):
  File "to_onnx.py", line 53, in <module>
    a,b=model(*x)
  File "/home/nvidia/.local/lib/python3.5/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/nvidia/DrQA/drqa/reader/rnn_reader.py", line 99, in forward
    x1_emb = self.embedding(x1)
  File "/home/nvidia/.local/lib/python3.5/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/nvidia/.local/lib/python3.5/site-packages/torch/nn/modules/sparse.py", line 108, in forward
    self.norm_type, self.scale_grad_by_freq, self.sparse)
  File "/home/nvidia/.local/lib/python3.5/site-packages/torch/nn/functional.py", line 1076, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
RuntimeError: Expected tensor for argument #1 'indices' to have scalar type Long; but got CPUFloatTensor instead (while checking arguments for embedding)

**Comment by ajfisch** [comment]
As the error suggests, the arguments are of the wrong type. `randn` returns a float tensor. The inputs are supposed to be (`LongTensor [b x d]`, `FloatTensor [b x d x f]`, `ByteTensor [b x d]`, `LongTensor [b x q]`, `ByteTensor [b x q]`).
