### ISSUE TITLE
when i run DrQA to process a question ,it will reload source and print memoryerror,how to fix it?

### ISSUE THREAD

**Issue by meibaotai** [facebookresearch/DrQA#168]
my system is windows10,RAM16GB,but it's not enough,i set the virtual memory is 20GB,but when i process a question,the QA can't work .i copy the run code in the txt.should i add my memory?
[Uploading the DrQA error.txt…]()

**Comment by meibaotai** [comment]
Thanks,the windows may not match the QA.We successed on linux.

**Comment by jcsturges** [comment]
I'm seeing the same thing on a brand new Ubuntu 18.04 install:

```11/28/2018 04:34:11 AM: [ Running on CPU only. ]
11/28/2018 04:34:11 AM: [ Initializing pipeline... ]
11/28/2018 04:34:11 AM: [ Initializing document ranker... ]
11/28/2018 04:34:11 AM: [ Loading /data/projects/DrQA/data/wikipedia/docs-tfidf-ngram=2-hash=16777216-tokenizer=simple.npz ]
Traceback (most recent call last):
  File "scripts/pipeline/interactive.py", line 70, in <module>
    tokenizer=args.tokenizer
  File "/data/projects/DrQA/drqa/pipeline/drqa.py", line 109, in __init__
    self.ranker = ranker_class(**ranker_opts)
  File "/data/projects/DrQA/drqa/retriever/tfidf_doc_ranker.py", line 37, in __init__
    matrix, metadata = utils.load_sparse_csr(tfidf_path)
  File "/data/projects/DrQA/drqa/retriever/utils.py", line 34, in load_sparse_csr
    matrix = sp.csr_matrix((loader['data'], loader['indices'],
  File "/home/james/.local/lib/python3.6/site-packages/numpy/lib/npyio.py", line 251, in __getitem__
    pickle_kwargs=self.pickle_kwargs)
  File "/home/james/.local/lib/python3.6/site-packages/numpy/lib/format.py", line 681, in read_array
    array = numpy.ndarray(count, dtype=dtype)
MemoryError
```

Running with 2 vCPU's and 8GB RAM, nothing else on the server. Is a GPU required? More base RAM?

**Comment by ajfisch** [comment]
You need at least around 15+ GB RAM.

**Comment by CS2015YWB** [comment]
> I'm seeing the same thing on a brand new Ubuntu 18.04 install:
> 
> ```
> 11/28/2018 04:34:11 AM: [ Initializing pipeline... ]
> 11/28/2018 04:34:11 AM: [ Initializing document ranker... ]
> 11/28/2018 04:34:11 AM: [ Loading /data/projects/DrQA/data/wikipedia/docs-tfidf-ngram=2-hash=16777216-tokenizer=simple.npz ]
> Traceback (most recent call last):
>   File "scripts/pipeline/interactive.py", line 70, in <module>
>     tokenizer=args.tokenizer
>   File "/data/projects/DrQA/drqa/pipeline/drqa.py", line 109, in __init__
>     self.ranker = ranker_class(**ranker_opts)
>   File "/data/projects/DrQA/drqa/retriever/tfidf_doc_ranker.py", line 37, in __init__
>     matrix, metadata = utils.load_sparse_csr(tfidf_path)
>   File "/data/projects/DrQA/drqa/retriever/utils.py", line 34, in load_sparse_csr
>     matrix = sp.csr_matrix((loader['data'], loader['indices'],
>   File "/home/james/.local/lib/python3.6/site-packages/numpy/lib/npyio.py", line 251, in __getitem__
>     pickle_kwargs=self.pickle_kwargs)
>   File "/home/james/.local/lib/python3.6/site-packages/numpy/lib/format.py", line 681, in read_array
>     array = numpy.ndarray(count, dtype=dtype)
> MemoryError
> ```
> Running with 2 vCPU's and 8GB RAM, nothing else on the server. Is a GPU required? More base RAM?

I have the same problem with you on ArchLinux.
```
➜  DrQA git:(master) ✗ python scripts/pipeline/interactive.py     
12/02/2018 06:38:36 PM: [ Running on CPU only. ]
12/02/2018 06:38:36 PM: [ Initializing pipeline... ]
12/02/2018 06:38:36 PM: [ Initializing document ranker... ]
12/02/2018 06:38:36 PM: [ Loading /home/leoyim/Desktop/DrQA/data/wikipedia/docs-tfidf-ngram=2-hash=16777216-tokenizer=simple.npz ]
Traceback (most recent call last):
  File "scripts/pipeline/interactive.py", line 70, in <module>
    tokenizer=args.tokenizer
  File "/home/leoyim/Desktop/DrQA/drqa/pipeline/drqa.py", line 109, in __init__
    self.ranker = ranker_class(**ranker_opts)
  File "/home/leoyim/Desktop/DrQA/drqa/retriever/tfidf_doc_ranker.py", line 37, in __init__
    matrix, metadata = utils.load_sparse_csr(tfidf_path)
  File "/home/leoyim/Desktop/DrQA/drqa/retriever/utils.py", line 34, in load_sparse_csr
    matrix = sp.csr_matrix((loader['data'], loader['indices'],
  File "/usr/lib/python3.7/site-packages/numpy/lib/npyio.py", line 251, in __getitem__
    pickle_kwargs=self.pickle_kwargs)
  File "/usr/lib/python3.7/site-packages/numpy/lib/format.py", line 681, in read_array
    array = numpy.ndarray(count, dtype=dtype)
MemoryError
```
Have you solved it?

**Comment by jcsturges** [comment]
Yea, the code is not very computationally efficient. It requires way too much in memory. One of (or the?) author said you need 15+ gigs of RAM though I haven’t confirmed that works. I ended up building my own lightweight version.

**Comment by nim456** [comment]
@jcsturges  can you pls share that efficient code which you have written .....it will be very helpful to all of us....

**Comment by ashtou** [comment]
Any updates on this? I ge the same `MemoryError` on Ubuntu 19.04 and with 32GB RAM

**Comment by krutikabapat** [comment]
@jcsturges can you please share your lightweight share, that would be really helpful
