### ISSUE TITLE
What is the cause of this error?

### ISSUE THREAD

**Issue by vrajjshah** [facebookresearch/DrQA#177]
python scripts/reader/interactive.py
09/20/2018 12:46:08 PM: [ CUDA enabled (GPU -1) ]
09/20/2018 12:46:08 PM: [ Initializing model... ]
09/20/2018 12:46:08 PM: [ Loading model /home/vraj/DrQA/data/reader/single.mdl ]
09/20/2018 12:46:11 PM: [ Initializing tokenizer... ]
Traceback (most recent call last):
  File "scripts/reader/interactive.py", line 55, in <module>
    predictor.cuda()
  File "/home/vraj/DrQA/drqa/reader/predictor.py", line 142, in cuda
    self.model.cuda()
  File "/home/vraj/DrQA/drqa/reader/model.py", line 469, in cuda
    self.network = self.network.cuda()
  File "/home/vraj/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 216, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/home/vraj/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 146, in _apply
    module._apply(fn)
  File "/home/vraj/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 146, in _apply
    module._apply(fn)
  File "/home/vraj/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 146, in _apply
    module._apply(fn)
  File "/home/vraj/anaconda3/lib/python3.6/site-packages/torch/nn/modules/rnn.py", line 123, in _apply
    self.flatten_parameters()
  File "/home/vraj/anaconda3/lib/python3.6/site-packages/torch/nn/modules/rnn.py", line 111, in flatten_parameters
    params = rnn.get_parameters(fn, handle, fn.weight_buf)
  File "/home/vraj/anaconda3/lib/python3.6/site-packages/torch/backends/cudnn/rnn.py", line 165, in get_parameters
    assert filter_dim_a.prod() == filter_dim_a[0]
AssertionError

**Comment by ajfisch** [comment]
Are you using CUDNN 7.1 with PyTorch 0.3.1? https://github.com/pytorch/pytorch/issues/5667

**Comment by vrajjshah** [comment]
Yes I got the error solved , thank you. For people having the same error, please install PyTorch 0.3.1 with CUDNN 7.0. I got the project working with CUDA V9.1.85
