### ISSUE TITLE
OSError: [Errno 12] Cannot allocate memory

### ISSUE THREAD

**Issue by bung87** [facebookresearch/DrQA#184]
```
python scripts/interactive.py --tokenizer spacy
11/01/2018 12:15:23 PM: [ Running on CPU only. ]
11/01/2018 12:15:23 PM: [ Initializing pipeline... ]
11/01/2018 12:15:23 PM: [ Initializing document ranker... ]
11/01/2018 12:15:23 PM: [ Loading /root/fbqa/data/wikipedia/docs-tfidf-ngram=2-hash=16777216-tokenizer=simple.npz ]
11/01/2018 12:17:12 PM: [ Initializing document reader... ]
11/01/2018 12:17:12 PM: [ Loading model /root/fbqa/data/reader/multitask.mdl ]
11/01/2018 12:17:16 PM: [ Initializing tokenizers and document retrievers... ]
Traceback (most recent call last):
  File "scripts/interactive.py", line 81, in <module>
    num_workers=args.num_workers
  File "/root/Envs/qa/lib/python3.5/site-packages/drqa/pipeline/drqa.py", line 140, in __init__
    initargs=(tok_class, tok_opts, db_class, db_opts, fixed_candidates)
  File "/usr/lib/python3.5/multiprocessing/context.py", line 118, in Pool
    context=self.get_context())
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 168, in __init__
    self._repopulate_pool()
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 233, in _repopulate_pool
    w.start()
  File "/usr/lib/python3.5/multiprocessing/process.py", line 105, in start
    self._popen = self._Popen(self)
  File "/usr/lib/python3.5/multiprocessing/context.py", line 267, in _Popen
    return Popen(process_obj)
  File "/usr/lib/python3.5/multiprocessing/popen_fork.py", line 20, in __init__
    self._launch(process_obj)
  File "/usr/lib/python3.5/multiprocessing/popen_fork.py", line 67, in _launch
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory
```
runs on a 16GB RAM machine

**Comment by ajfisch** [comment]
Hm --

- Do you have overcommit enabled? If not, try doing that.
- What version of spaCy are you using? Try downgrading to a lower version (e.g. pip install -U spacy==1.9.0). Perhaps extra libraries are being loading.
- Try running with just one worker thread: you can set that [here](https://github.com/facebookresearch/DrQA/blob/master/scripts/pipeline/interactive.py#L64-L71) by adding `num_workers=1`.

**Comment by bung87** [comment]
`echo 1 > /proc/sys/vm/overcommit_memory` solve the problem.
`process('What is question answering?')` answers `QA`, not same as document either the results I run on my Mac  
`process('Who was the winning pitcher in the 1956 World Series?')` seems cant get results tooks minutes seems wont finish.

**Comment by bung87** [comment]
hmm.. the 16G RAM server seems runs more slower than my 8G RAM Mac, and cant get results.

**Comment by bung87** [comment]
ok resolved ,I changed some cli argument that has default value ,cause it not work. it takes about 6 seconds on server , thank you!
