### ISSUE TITLE
PosixPath error

### ISSUE THREAD

**Issue by voquocbang** [facebookresearch/DrQA#192]
I'm trying to install DrQA on Windows and got this error:

C:\Programs\Anaconda2\envs\DrQA-master\python.exe C:/Works/DrQA-master/test.py
Traceback (most recent call last):
  File "C:/Works/DrQA-master/test.py", line 1, in <module>
    from drqa.tokenizers import CoreNLPTokenizer
  File "C:\Works\DrQA-master\drqa\__init__.py", line 18, in <module>
    os.path.join(PosixPath(__file__).absolute().parents[1].as_posix(), 'data')
  File "C:\Programs\Anaconda2\envs\DrQA-master\lib\pathlib.py", line 1004, in __new__
    % (cls.__name__,))
NotImplementedError: cannot instantiate 'PosixPath' on your system

Can anyone help me with this?

**Comment by ajfisch** [comment]
Sorry, DrQa is [not supported for Windows](https://github.com/facebookresearch/DrQA#installing-drqa).
