### ISSUE TITLE
Syntax error due to keyword async for python 3.7

### ISSUE THREAD

**Issue by ChelseaZheng** [facebookresearch/DrQA#194]
The error comes when I run 
`python3 scripts/pipeline/interactive.py`

The full log is:

`Traceback (most recent call last):
  File "scripts/pipeline/interactive.py", line 16, in <module>
    from drqa import pipeline
  File "/Users/fionazheng/quadrant2/DrQA/drqa/__init__.py", line 20, in <module>
    from . import tokenizers
  File "/Users/fionazheng/quadrant2/DrQA/drqa/tokenizers/__init__.py", line 20, in <module>
    from .corenlp_tokenizer import CoreNLPTokenizer
  File "/Users/fionazheng/quadrant2/DrQA/drqa/tokenizers/corenlp_tokenizer.py", line 14, in <module>
    import pexpect
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pexpect/__init__.py", line 75, in <module>
    from .pty_spawn import spawn, spawnu
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pexpect/pty_spawn.py", line 14, in <module>
    from .spawnbase import SpawnBase
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pexpect/spawnbase.py", line 224
    def expect(self, pattern, timeout=-1, searchwindowsize=-1, async=False):
                                                                   ^
SyntaxError: invalid syntax
`

Could someone help with this?

Thanks!

**Comment by ajfisch** [comment]
Ah -- this is a problem for python 3.6 --> 3.7. In the version of pytorch this repo was developed with, async is a function argument. In 3.7 it is a reserved keyword. If you use python 3.6 it should work (and pytorch 0.3.0 or 0.3.1).

**Comment by jabbany** [comment]
Replacing `async=True` with `non_blocking=True` in offending files also works.

**Comment by prdwb** [comment]
Upgrading pexpect to 4.7.0 also seems to work. It passed the corenlp tokenization example.

**Comment by Sir-Ignis** [comment]
Replacing all occurrences of ``async`` with ``aysnc_`` in file ``spawnbase.py`` fixed this error.
