### ISSUE TITLE
Error while rumnning train.py 

### ISSUE THREAD

**Issue by Atul997** [facebookresearch/DrQA#198]
While running `python3 scripts/reader/train.py  --embedding-file glove.840B.300d.txt --tune-partial 1000 --gpu 1` 

I am getting error 

`WARN: fix_embeddings set to False as tune_partial > 0.
02/20/2019 05:07:45 PM: [ COMMAND: scripts/reader/train.py --embed-dir /home/atul/DrQA/data/embeddings/ --tune-partial 1000 --gpu 1 ]
02/20/2019 05:07:45 PM: [ ---------------------------------------------------------------------------------------------------- ]
02/20/2019 05:07:45 PM: [ Load data files ]
02/20/2019 05:08:08 PM: [ Num train examples = 86832 ]
02/20/2019 05:08:12 PM: [ Num dev examples = 10570 ]
02/20/2019 05:08:12 PM: [ ---------------------------------------------------------------------------------------------------- ]
02/20/2019 05:08:12 PM: [ Training model from scratch... ]
02/20/2019 05:08:12 PM: [ ---------------------------------------------------------------------------------------------------- ]
02/20/2019 05:08:12 PM: [ Generate features ]
02/20/2019 05:08:20 PM: [ Num features = 62 ]
02/20/2019 05:08:20 PM: [ {'pos=JJR': 35, 'pos=POS': 12, 'pos=NN': 6, 'pos=:': 32, 'pos=WP$': 43, 'pos=RB': 3, 'pos=VBN': 17, 'pos=RBS': 28, 'pos=UH': 44, 'in_question': 0, 'pos=VBD': 23, 'pos=CC': 13, 'pos=JJS': 31, 'pos=.': 9, 'pos=RP': 37, 'pos=VBZ': 7, 'ner=ORGANIZATION': 54, 'pos=WRB': 22, "pos=''": 20, 'pos=WDT': 26, 'ner=MONEY': 59, 'ner=LOCATION': 51, 'tf': 61, 'pos=VBG': 14, 'pos=,': 4, 'pos=NNP': 11, 'pos=LS': 47, 'pos=NNPS': 19, 'ner=PERSON': 50, 'ner=ORDINAL': 57, 'ner=MISC': 49, 'pos=EX': 39, 'ner=TIME': 60, 'ner=DATE': 52, 'ner=DURATION': 56, 'pos=NNS': 16, 'pos=FW': 42, 'pos=TO': 21, 'pos=CD': 24, 'pos=PRP': 15, 'ner=O': 48, 'in_question_uncased': 1, 'pos=``': 18, 'ner=SET': 55, 'pos=$': 36, 'pos=PDT': 45, 'ner=NUMBER': 53, 'pos=WP': 34, 'pos=VB': 30, 'pos=VBP': 29, 'pos=JJ': 8, 'ner=PERCENT': 58, 'pos=SYM': 46, 'pos=#': 40, 'pos=PRP$': 33, 'pos=DT': 5, 'in_question_lemma': 2, 'pos=-LRB-': 25, 'pos=IN': 10, 'pos=-RRB-': 27, 'pos=RBR': 41, 'pos=MD': 38} ]
02/20/2019 05:08:20 PM: [ ---------------------------------------------------------------------------------------------------- ]
02/20/2019 05:08:20 PM: [ Build dictionary ]
02/20/2019 05:08:20 PM: [ Restricting to words in /home/atul/DrQA/data/embeddings/glove.840B.300d.txt ]
02/20/2019 05:08:45 PM: [ Num words in set = 757064 ]
02/20/2019 05:08:54 PM: [ Num words = 88431 ]
02/20/2019 05:08:57 PM: [ Loading pre-trained embeddings for 88429 words from /home/atul/DrQA/data/embeddings/glove.840B.300d.txt ]
02/20/2019 05:09:09 PM: [ WARN: Duplicate embedding found for Kṛṣṇa ]
02/20/2019 05:09:13 PM: [ WARN: Duplicate embedding found for · ]
02/20/2019 05:09:16 PM: [ WARN: Duplicate embedding found for ; ]
02/20/2019 05:09:17 PM: [ WARN: Duplicate embedding found for à ]
02/20/2019 05:09:25 PM: [ WARN: Duplicate embedding found for José ]
Traceback (most recent call last):
  File "scripts/reader/train.py", line 542, in <module>
    main(args)
  File "scripts/reader/train.py", line 402, in main
    model = init_from_scratch(args, train_exs, dev_exs)
  File "scripts/reader/train.py", line 197, in init_from_scratch
    model.load_embeddings(word_dict.tokens(), args.embedding_file)
  File "/home/atul/DrQA/drqa/reader/model.py", line 109, in load_embeddings
    assert(len(parsed) == embedding.size(1) + 1)
AssertionError
`
How to resolve this.?
Thanks

**Comment by krutikabapat** [comment]
@Atul997 Did you get solution to this problem? I am facing the same issue

**Comment by Atul997** [comment]
No
