### ISSUE TITLE
getting error while running scripts/pipeline/interactive someone please help

### ISSUE THREAD

**Issue by pavankjois** [facebookresearch/DrQA#199]
when i try to run the code im getting this error my cuda version is  10.0.130 and my pytorch version is 1.0.0a0
some one help me 
paperspace@psochxboa:~/DRQA$ sudo python scripts/pipeline/interactive.py
02/21/2019 11:17:37 PM: [ CUDA enabled (GPU -1) ]
02/21/2019 11:17:37 PM: [ Initializing pipeline... ]
02/21/2019 11:17:37 PM: [ Initializing document ranker... ]
02/21/2019 11:17:37 PM: [ Loading /home/paperspace/DRQA/data/wikipedia/docs-tfidf-ngram=2-hash=16777216-tokenizer=simple.npz ]
02/21/2019 11:18:17 PM: [ Initializing document reader... ]
02/21/2019 11:18:17 PM: [ Loading model /home/paperspace/DRQA/data/reader/multitask.mdl ]
Traceback (most recent call last):
  File "scripts/pipeline/interactive.py", line 70, in <module>
    tokenizer=args.tokenizer
  File "/home/paperspace/DRQA/drqa/pipeline/drqa.py", line 120, in __init__
    self.reader.cuda()
  File "/home/paperspace/DRQA/drqa/reader/model.py", line 469, in cuda
    self.network = self.network.cuda()
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 258, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 185, in _apply
    module._apply(fn)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 185, in _apply
    module._apply(fn)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 185, in _apply
    module._apply(fn)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/rnn.py", line 117, in _apply
    self.flatten_parameters()
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/rnn.py", line 90, in flatten_parameters
    if not any_param.is_cuda or not torch.backends.cudnn.is_acceptable(any_param):
  File "/usr/local/lib/python3.6/dist-packages/torch/backends/cudnn/__init__.py", line 92, in is_acceptable
    if _libcudnn() is None:
  File "/usr/local/lib/python3.6/dist-packages/torch/backends/cudnn/__init__.py", line 58, in _libcudnn
    'but linked against {}'.format(compile_version, __cudnn_version))
RuntimeError: cuDNN version mismatch: PyTorch was compiled against 7300 but linked against 7402

thank you

**Comment by jscheidtmann** [comment]
Check your pytorch and CUDA installation or run with `--no-cuda`
