### ISSUE TITLE
Latest commit will not run with out GPU

### ISSUE THREAD

**Issue by NatCusack** [facebookresearch/DrQA#207]
Most recent upgrade to Pytorch 1.0 causes problems when trying to run code without GPU. 
pipline/interactive.py runs as expected untill I ask a question:
`>>> process("What is the capital of Ireland?")
03/13/2019 10:55:10 AM: [ Processing 1 queries... ]
03/13/2019 10:55:10 AM: [ Retrieving top 5 docs... ]
03/13/2019 10:55:12 AM: [ Reading 664 paragraphs... ]
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "scripts/pipeline/interactive.py", line 81, in process
    question, candidates, top_n, n_docs, return_context=True
  File "/home/domainproxy/NateCusack/test/drqa/pipeline/drqa.py", line 190, in process
    top_n, n_docs, return_context
  File "/home/domainproxy/NateCusack/test/drqa/pipeline/drqa.py", line 270, in process_batch
    handle = self.reader.predict(batch, async_pool=self.processes)
  File "/home/domainproxy/NateCusack/test/drqa/reader/model.py", line 287, in predict
    for e in ex[:5]]
  File "/home/domainproxy/NateCusack/test/drqa/reader/model.py", line 287, in <listcomp>
    for e in ex[:5]]
  File "/home/domainproxy/NateCusack/test/lib/python3.6/site-packages/torch/cuda/__init__.py", line 161, in _lazy_init
    _check_driver()
  File "/home/domainproxy/NateCusack/test/lib/python3.6/site-packages/torch/cuda/__init__.py", line 82, in _check_driver
    http://www.nvidia.com/Download/index.aspx""")
AssertionError:
Found no NVIDIA driver on your system. Please check that you
have an NVIDIA GPU and installed a driver from
http://www.nvidia.com/Download/index.aspx
`
same error occurs when I run the system with the `--no-cuda` assignment

Here is a list of my installed packages in the virtual environment: 
`drqa           0.1.0       /redacted/path/to/drqa
elasticsearch  6.3.1
nltk           3.4
numpy          1.16.2
pexpect        4.2.1
pip            19.0.3
pkg-resources  0.0.0
prettytable    0.7.2
ptyprocess     0.6.0
regex          2019.3.12
scikit-learn   0.20.3
scipy          1.2.1
setuptools     40.8.0
singledispatch 3.4.0.3
six            1.12.0
termcolor      1.1.0
torch          1.0.1.post2
tqdm           4.31.1
urllib3        1.24.1
wheel          0.33.1
`
Thanks for sharing this project

**Comment by ajfisch** [comment]
Fixed in #206

**Comment by NatCusack** [comment]
Working now thanks!
