### ISSUE TITLE
standalone reader not working with the latest StanfordNLP tokenizer (stanford-corenlp-full-2018-10-05)

### ISSUE THREAD

**Issue by mpandeydev** [facebookresearch/DrQA#219]
python scripts/reader/interactive.py 
04/18/2019 06:51:23 PM: [ CUDA enabled (GPU -1) ]
04/18/2019 06:51:23 PM: [ Initializing model... ]
04/18/2019 06:51:23 PM: [ Loading model /home/mpandey/ServiceNet/drqa_dev/DrQA/data/reader/single.mdl ]
04/18/2019 06:51:23 PM: [ Initializing tokenizer... ]

DrQA Interactive Document Reader Module
>> process(document, question, candidates=None, top_n=1)
>> usage()

>>> text = "Mary had a little lamb, whose fleece was white as snow. And everywhere that Mary went the lamb was sure to go."
>>> question = "What color is Mary's lamb?"
>>> process(text, question)
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "scripts/reader/interactive.py", line 65, in process
    predictions = predictor.predict(document, question, candidates, top_n)
  File "/home/mpandey/ServiceNet/drqa_dev/DrQA/drqa/reader/predictor.py", line 88, in predict
    results = self.predict_batch([(document, question, candidates,)], top_n)
  File "/home/mpandey/ServiceNet/drqa_dev/DrQA/drqa/reader/predictor.py", line 107, in predict_batch
    q_tokens = list(map(self.tokenizer.tokenize, questions))
  File "/home/mpandey/ServiceNet/drqa_dev/DrQA/drqa/tokenizers/corenlp_tokenizer.py", line 101, in tokenize
    output = json.loads(output[start:].decode('utf-8'))
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 2 column 1 (char 1)

BTW, If I use tokenzier following the installation instruction, I get TIMEOUT error as reported in #218

**Comment by ajfisch** [comment]
Yeah, it's only tested with the version linked in the repo download. Hope to update to more robust default tokenizer soon.
