### ISSUE TITLE
Get Memory Error when running interactive.py

### ISSUE THREAD

**Issue by RahulSinghYYC** [facebookresearch/DrQA#223]
Hi Everyone 
I am getting Memory error when i try to execute interactive.py Any help would be great. 
Please see error below
/usr/bin/python3.5 /home/deeplearning/DrQA/scripts/pipeline/interactive.py
06/13/2019 09:54:00 AM: [ Running on CPU only. ]
06/13/2019 09:54:00 AM: [ Initializing pipeline... ]
06/13/2019 09:54:00 AM: [ Initializing document ranker... ]
06/13/2019 09:54:00 AM: [ Loading /home/deeplearning/DrQA/data/wikipedia/docs-tfidf-ngram=2-hash=16777216-tokenizer=simple.npz ]
Traceback (most recent call last):
  File "/home/deeplearning/DrQA/scripts/pipeline/interactive.py", line 70, in <module>
    tokenizer=args.tokenizer
  File "/home/deeplearning/DrQA/drqa/pipeline/drqa.py", line 109, in __init__
    self.ranker = ranker_class(**ranker_opts)
  File "/home/deeplearning/DrQA/drqa/retriever/tfidf_doc_ranker.py", line 37, in __init__
    matrix, metadata = utils.load_sparse_csr(tfidf_path)
  File "/home/deeplearning/DrQA/drqa/retriever/utils.py", line 34, in load_sparse_csr
    matrix = sp.csr_matrix((loader['data'], loader['indices'],
  File "/usr/local/lib/python3.5/dist-packages/numpy/lib/npyio.py", line 235, in __getitem__
    pickle_kwargs=self.pickle_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/numpy/lib/format.py", line 674, in read_array
    array = numpy.ndarray(count, dtype=dtype)
MemoryError

Process finished with exit code 1

**Comment by ajfisch** [comment]
How much RAM do you have?

**Comment by RahulSinghYYC** [comment]
> How much RAM do you have?

I have 16 GB RAM

**Comment by ajfisch** [comment]
That *should* be enough, though just enough. Looks like you ran out of memory. Make sure you don't have any other processes running that are taking up RAM, so you have the full 16Gb. You might also have to enable overcommit.

**Comment by ajfisch** [comment]
Closing since this hasnt been updated in awhile.
