### ISSUE TITLE
error while importing drqa 

### ISSUE THREAD

**Issue by Ravikiran2611** [facebookresearch/DrQA#227]
git clone https://github.com/facebookresearch/DrQA.git
cd DrQA; 
pip install -r requirements.txt;
python setup.py develop

HI AFTER THE EXECUTING THE ABOVE INSTRUCTION , I OPEN THE PYTHON INTERPRETER IN THE TERMINAL ANF TYPE

import drqa

I GET THE ERROR 

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/local/ZOHOCORP/ravi-9151/DrQA/drqa/__init__.py", line 20, in <module>
    from . import tokenizers
  File "/home/local/ZOHOCORP/ravi-9151/DrQA/drqa/tokenizers/__init__.py", line 20, in <module>
    from .corenlp_tokenizer import CoreNLPTokenizer
  File "/home/local/ZOHOCORP/ravi-9151/DrQA/drqa/tokenizers/corenlp_tokenizer.py", line 14, in <module>
    import pexpect
  File "/home/local/ZOHOCORP/ravi-9151/anaconda3/envs/drqa/lib/python3.7/site-packages/pexpect/__init__.py", line 75, in <module>
    from .pty_spawn import spawn, spawnu
  File "/home/local/ZOHOCORP/ravi-9151/anaconda3/envs/drqa/lib/python3.7/site-packages/pexpect/pty_spawn.py", line 14, in <module>
    from .spawnbase import SpawnBase
  File "/home/local/ZOHOCORP/ravi-9151/anaconda3/envs/drqa/lib/python3.7/site-packages/pexpect/spawnbase.py", line 224
    def expect(self, pattern, timeout=-1, searchwindowsize=-1, async=False):
                                                                   ^
SyntaxError: invalid syntax

CAN ANYONE HELP ME WHAT TO DO 
THANKS IN ADVANCE!!!!!!!!!!!!!!!!

**Comment by ajfisch** [comment]
This sounds like a python 3.7 conflict. Could you downgrade to 3.6?

**Comment by Ravikiran2611** [comment]
@ajfisch  THANKS SO MUCH , I WORKED FOR ME
