### ISSUE TITLE
setup.py gives UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 18175: character maps to <undefined>

### ISSUE THREAD

**Issue by Code4SAFrankie** [facebookresearch/DrQA#232]
Running `python setup.py develop` on Windows 10 gives the following error:

```
Traceback (most recent call last):
  File "setup.py", line 12, in <module>
    readme = f.read()
  File "E:\WPy-3710\python-3.7.1.amd64\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 18175: character maps to <undefined>

```

I also did the following before running it:

```
set LANGUAGE=en_US.UTF-8
set LC_ALL=en_US.UTF-8
set LANG=en_US.UTF-8
set LC_TYPE=en_US.UTF-8

```

`sys.getdefaultencoding()` and `sys.stdout.encoding` both gives:

`'utf-8'`

I am on:

WinPython 3.7.1 (v3.7.1:260ec2c36a, Oct 20 2018, 14:57:15) [MSC v.1915 64 bit (AMD64)] on win32
Windows 10 64-bit 1903

**Comment by GeorgeG92** [comment]
I have the exact same problem (... byte 0x9d in position 18529). I cloned the repo and tried running 
python setup.py develop
I am using Windows 10 64-bit with Python 3.7.5

**Comment by krutikabapat** [comment]
I had the same problem. I am using Windows 10 64-bit with Python 3.7.5. Fixed the error by making the following changes. In setup.py make the following changes,

Replace ``` with open('README.md') as f: ```
with 
```  with open('README.md', encoding='utf8') as f: ```
Replace ``` with open('LICENSE', encoding='utf8') as f: ```
with  ``` with open('LICENSE') as f: ```

Replace ``` with open('requirements.txt') as f: ```
with ``` with open('requirements.txt', encoding='utf8') as f: ```
