### ISSUE TITLE
BlockingIOError: [Errno 11] Resource temporarily unavailable while excuting scirpts/pipeline/interaction.py

### ISSUE THREAD

**Issue by LxinG-YY** [facebookresearch/DrQA#235]
When I executed scirpts/pipeline/interaction.py， “BlockingIOError: [Errno 11] Resource temporarily unavailable” was raised. Can I get any help? Thx

Log as below:
(drqa_venv) [liangxin@kd03 DrQA_mac]$ python scripts/pipeline/interactive.py --gpu 2
12/06/2019 10:50:49 AM: [ CUDA enabled (GPU 2) ]
12/06/2019 10:50:49 AM: [ Initializing pipeline... ]
12/06/2019 10:50:49 AM: [ Initializing document ranker... ]
12/06/2019 10:50:49 AM: [ Loading /home/liangxin/codes/DrQA_mac/data/wikipedia/docs-tfidf-ngram=2-hash=16777216-tokenizer=simple.npz ]
12/06/2019 10:51:27 AM: [ Initializing document reader... ]
12/06/2019 10:51:27 AM: [ Loading model /home/liangxin/codes/DrQA_mac/data/reader/multitask.mdl ]
12/06/2019 10:51:33 AM: [ Initializing tokenizers and document retrievers... ]
Process ForkPoolWorker-50:
Traceback (most recent call last):
  File "/usr/lib64/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib64/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib64/python3.6/multiprocessing/pool.py", line 103, in worker
    initializer(*initargs)
  File "/home/liangxin/codes/DrQA_mac/drqa/pipeline/drqa.py", line 39, in init
    PROCESS_TOK = tokenizer_class(**tokenizer_opts)
  File "/home/liangxin/codes/DrQA_mac/drqa/tokenizers/corenlp_tokenizer.py", line 33, in __init__
    self._launch()
  File "/home/liangxin/codes/DrQA_mac/drqa/tokenizers/corenlp_tokenizer.py", line 55, in _launch
    self.corenlp = pexpect.spawn('/bin/bash', maxread=100000, timeout=60)
  File "/home/liangxin/drqa_venv/lib64/python3.6/site-packages/pexpect/pty_spawn.py", line 197, in __init__
    self._spawn(command, args, preexec_fn, dimensions)
  File "/home/liangxin/drqa_venv/lib64/python3.6/site-packages/pexpect/pty_spawn.py", line 297, in _spawn
    cwd=self.cwd, **kwargs)
  File "/home/liangxin/drqa_venv/lib64/python3.6/site-packages/pexpect/pty_spawn.py", line 308, in _spawnpty
    return ptyprocess.PtyProcess.spawn(args, **kwargs)
  File "/home/liangxin/drqa_venv/lib64/python3.6/site-packages/ptyprocess/ptyprocess.py", line 226, in spawn
    pid, fd = pty.fork()
  File "/usr/lib64/python3.6/pty.py", line 97, in fork
    pid = os.fork()
BlockingIOError: [Errno 11] Resource temporarily unavailable
Process ForkPoolWorker-51:
Traceback (most recent call last):
  File "/usr/lib64/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib64/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib64/python3.6/multiprocessing/pool.py", line 103, in worker
    initializer(*initargs)
  File "/home/liangxin/codes/DrQA_mac/drqa/pipeline/drqa.py", line 39, in init
    PROCESS_TOK = tokenizer_class(**tokenizer_opts)
  File "/home/liangxin/codes/DrQA_mac/drqa/tokenizers/corenlp_tokenizer.py", line 33, in __init__
    self._launch()
  File "/home/liangxin/codes/DrQA_mac/drqa/tokenizers/corenlp_tokenizer.py", line 55, in _launch
    self.corenlp = pexpect.spawn('/bin/bash', maxread=100000, timeout=60)
  File "/home/liangxin/drqa_venv/lib64/python3.6/site-packages/pexpect/pty_spawn.py", line 197, in __init__
    self._spawn(command, args, preexec_fn, dimensions)
  File "/home/liangxin/drqa_venv/lib64/python3.6/site-packages/pexpect/pty_spawn.py", line 297, in _spawn
    cwd=self.cwd, **kwargs)
  File "/home/liangxin/drqa_venv/lib64/python3.6/site-packages/pexpect/pty_spawn.py", line 308, in _spawnpty
    return ptyprocess.PtyProcess.spawn(args, **kwargs)
  File "/home/liangxin/drqa_venv/lib64/python3.6/site-packages/ptyprocess/ptyprocess.py", line 226, in spawn
    pid, fd = pty.fork()
  File "/usr/lib64/python3.6/pty.py", line 97, in fork
    pid = os.fork()
BlockingIOError: [Errno 11] Resource temporarily unavailable
Traceback (most recent call last):
  File "scripts/pipeline/interactive.py", line 70, in <module>
    tokenizer=args.tokenizer
  File "/home/liangxin/codes/DrQA_mac/drqa/pipeline/drqa.py", line 146, in __init__
    initargs=(tok_class, tok_opts, db_class, db_opts, fixed_candidates)
  File "/usr/lib64/python3.6/multiprocessing/context.py", line 119, in Pool
    context=self.get_context())
  File "/usr/lib64/python3.6/multiprocessing/pool.py", line 174, in __init__
    self._repopulate_pool()
  File "/usr/lib64/python3.6/multiprocessing/pool.py", line 239, in _repopulate_pool
    w.start()
  File "/usr/lib64/python3.6/multiprocessing/process.py", line 105, in start
    self._popen = self._Popen(self)
  File "/usr/lib64/python3.6/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
  File "/usr/lib64/python3.6/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/usr/lib64/python3.6/multiprocessing/popen_fork.py", line 66, in _launch
    self.pid = os.fork()
BlockingIOError: [Errno 11] Resource temporarily unavailable

**Comment by Gituser143** [comment]
@LxinG-YY Could you please elaborate on how the `BlockingIOError: [Errno 11] Resource temporarily unavailable` issue was fixed?
