### ISSUE TITLE
cuda execution failed

### ISSUE THREAD

**Issue by cghuisunshine** [facebookresearch/DrQA#25]
python scripts/pipeline/interactive.py 
08/12/2017 04:22:03 PM: [ CUDA enabled (GPU -1) ]
08/12/2017 04:22:03 PM: [ Initializing pipeline... ]
08/12/2017 04:22:03 PM: [ Initializing document ranker... ]
08/12/2017 04:22:03 PM: [ Loading /home/chenguanghui/DrQA/data/wikipedia/docs-tfidf-ngram=2-hash=16777216-tokenizer=simple.npz ]
08/12/2017 04:22:29 PM: [ Initializing model... ]
08/12/2017 04:22:29 PM: [ Loading model /home/chenguanghui/DrQA/data/reader/multitask.mdl ]
08/12/2017 04:22:36 PM: [ Initializing tokenizers and document retrievers... ]

Interactive DrQA
>> process(question, candidates=None, top_n=1, n_docs=5)
>> usage()

>>> process('Mars')
08/12/2017 04:25:06 PM: [ Processing 1 queries... ]
08/12/2017 04:25:06 PM: [ Retrieving top 5 docs... ]
08/12/2017 04:25:08 PM: [ Reading 421 paragraphs... ]
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "scripts/pipeline/interactive.py", line 81, in process
    question, candidates, top_n, n_docs, return_context=True
  File "/home/chenguanghui/DrQA/drqa/pipeline/drqa.py", line 184, in process
    top_n, n_docs, return_context
  File "/home/chenguanghui/DrQA/drqa/pipeline/drqa.py", line 264, in process_batch
    handle = self.reader.predict(batch, async_pool=self.processes)
  File "/home/chenguanghui/DrQA/drqa/reader/model.py", line 287, in predict
    score_s, score_e = self.network(*inputs)
  File "/home/chenguanghui/anaconda3/lib/python3.5/site-packages/torch/nn/modules/module.py", line 224, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/chenguanghui/DrQA/drqa/reader/rnn_reader.py", line 122, in forward
    doc_hiddens = self.doc_rnn(torch.cat(drnn_input, 2), x1_mask)
  File "/home/chenguanghui/anaconda3/lib/python3.5/site-packages/torch/nn/modules/module.py", line 224, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/chenguanghui/DrQA/drqa/reader/layers.py", line 61, in forward
    output = self._forward_padded(x, x_mask)
  File "/home/chenguanghui/DrQA/drqa/reader/layers.py", line 137, in _forward_padded
    outputs.append(self.rnns[i](rnn_input)[0])
  File "/home/chenguanghui/anaconda3/lib/python3.5/site-packages/torch/nn/modules/module.py", line 224, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/chenguanghui/anaconda3/lib/python3.5/site-packages/torch/nn/modules/rnn.py", line 162, in forward
    output, hidden = func(input, self.all_weights, hx)
  File "/home/chenguanghui/anaconda3/lib/python3.5/site-packages/torch/nn/_functions/rnn.py", line 351, in forward
    return func(input, *fargs, **fkwargs)
  File "/home/chenguanghui/anaconda3/lib/python3.5/site-packages/torch/autograd/function.py", line 284, in _do_forward
    flat_output = super(NestedIOFunction, self)._do_forward(*flat_input)
  File "/home/chenguanghui/anaconda3/lib/python3.5/site-packages/torch/autograd/function.py", line 306, in forward
    result = self.forward_extended(*nested_tensors)
  File "/home/chenguanghui/anaconda3/lib/python3.5/site-packages/torch/nn/_functions/rnn.py", line 293, in forward_extended
    cudnn.rnn.forward(self, input, hx, weight, output, hy)
  File "/home/chenguanghui/anaconda3/lib/python3.5/site-packages/torch/backends/cudnn/rnn.py", line 319, in forward
    ctypes.c_void_p(workspace.data_ptr()), workspace.size(0)
  File "/home/chenguanghui/anaconda3/lib/python3.5/site-packages/torch/backends/cudnn/__init__.py", line 255, in check_error
    raise CuDNNError(status)
torch.backends.cudnn.CuDNNError: 8: b'CUDNN_STATUS_EXECUTION_FAILED'
>>>

**Comment by cghuisunshine** [comment]
And my CUDA and CUDNN version listed below:

chenguanghui@dgx-1:~$ cat /usr/local/cuda/version.txt
CUDA Version 8.0.61
chenguanghui@dgx-1:~$ cat /usr/local/cuda/include/cudnn.h | grep CUDNN_MAJOR -A 2
#define CUDNN_MAJOR      5
#define CUDNN_MINOR      1
#define CUDNN_PATCHLEVEL 10
--
#define CUDNN_VERSION    (CUDNN_MAJOR * 1000 + CUDNN_MINOR * 100 + CUDNN_PATCHLEVEL)

#include "driver_types.h"

**Comment by ajfisch** [comment]
This seems to be a problem with your torch/cuda/cudnn install, not DrQA. I'd direct these questions to the pytorch issues page and/or forums.

My immediate suggestion is to make sure that you properly installed pytorch. (conda install -y pytorch cuda80 -c soumith ).

**Comment by cghuisunshine** [comment]
I installed pytorch as above(conda install -y pytorch cuda80 -c soumith) and I also ran some rnn examples. All were O.K. Should I raise the question to pytorch?

**Comment by ajfisch** [comment]
Yes, I would raise it to pytorch if you can't solve it, but only after you've done some digging and identified a short snippet to reproduce your issue. Did you try running RNNs with both CPU and CUDA inputs?
