### ISSUE TITLE
 OSError: [Errno 12] Cannot allocate memory

### ISSUE THREAD

**Issue by nyhDudu** [facebookresearch/DrQA#253]
when I run python scripts / pipeline / interactive.py, I get OSError: [Errno 12] Cannot allocate memory, I do n’t know how to solve it, can you tell me, thank you

**Comment by Martin36** [comment]
I have the same problem. I run a Ubuntu subsystem on Windows 10.

Here is the stack trace: 

```
Traceback (most recent call last):
  File "scripts/pipeline/interactive.py", line 70, in <module>
    tokenizer=args.tokenizer
  File "/mnt/d/Documents/NLP/DrQA/drqa/pipeline/drqa.py", line 146, in __init__
    initargs=(tok_class, tok_opts, db_class, db_opts, fixed_candidates)
  File "/home/martin/miniconda3/lib/python3.7/multiprocessing/context.py", line 119, in Pool
    context=self.get_context())
  File "/home/martin/miniconda3/lib/python3.7/multiprocessing/pool.py", line 176, in __init__
    self._repopulate_pool()
  File "/home/martin/miniconda3/lib/python3.7/multiprocessing/pool.py", line 241, in _repopulate_pool
    w.start()
  File "/home/martin/miniconda3/lib/python3.7/multiprocessing/process.py", line 112, in start
    self._popen = self._Popen(self)
  File "/home/martin/miniconda3/lib/python3.7/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
  File "/home/martin/miniconda3/lib/python3.7/multiprocessing/popen_fork.py", line 20, in __init__
    self._launch(process_obj)
  File "/home/martin/miniconda3/lib/python3.7/multiprocessing/popen_fork.py", line 70, in _launch
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory
```
