### ISSUE TITLE
When I ran python setup.py develop,it happened errors

### ISSUE THREAD

**Issue by liujinyan12** [facebookresearch/DrQA#31]
When I  ran python setup.py develop, it happened errors like this:
root@e93927f380d3:~/DrQA# python setup.py develop
Traceback (most recent call last):
  File "setup.py", line 12, in <module>
    readme = f.read()
  File "/root/anaconda3/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 8661: ordinal not in range(128)

How can I do to fix that problems.
Thank you.

**Comment by ajfisch** [comment]
It seems like your default encoding is `ascii` where in Python 3 it should be `utf-8`. You should make sure whatever factors specific to you environment (environment variables perhaps?) are fixed such that `open()` uses `utf-8` encoding by default.

**Comment by liujinyan12** [comment]
Yes,you are right.I have solved that problem.Thank you.

**Comment by kickbox** [comment]
`open(embedding_file, encoding='utf-8')` seems to work for now. Would this have any global effects when changing the embedding file? 

I as this especially because there seems to different encoding for glove and fastText..

```
bash-4.2$ file -i *
glove.840B.300d.txt: text/plain; charset=us-ascii
wiki.en.vec:         text/plain; charset=utf-8

```

**Comment by kickbox** [comment]
I was able to resolve this. The problem was with my unix system which had a different encoding set, which python 3 followed.

I had to reset the encoding of my system by the below command;

```
export LANGUAGE=en_US.UTF-8
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export LC_TYPE=en_US.UTF-8
```

check

```
python
>>> import sys
>>> sys.stdout.encoding
'UTF-8'
```

**Comment by erincullen5** [comment]
Thank you! This helped

**Comment by snailcoder** [comment]
Thanks @kickbox ! 
When I run:
`python setup.py develop`

I got a similar error:

> Traceback (most recent call last):
  File "setup.py", line 12, in <module>
    readme = f.read()
  File "/home/ubuntu/anaconda2/envs/py36/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 8698: ordinal not in range(128)

And I resolved it by exporting some variable as you did.

**Comment by hard-fault** [comment]
Use this as **setup.py**

```
#!/usr/bin/env python3
# Copyright 2017-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the license found in the
# LICENSE file in the root directory of this source tree.

from setuptools import setup, find_packages
import sys

with open('README.md', encoding="utf-8") as f:
    readme = f.read()

with open('LICENSE', encoding="utf-8") as f:
    license = f.read()

with open('requirements.txt', encoding="utf-8") as f:
    reqs = f.read()

setup(
    name='drqa',
    version='0.1.0',
    description='Reading Wikipedia to Answer Open-Domain Questions',
    long_description=readme,
    license=license,
    python_requires='>=3.5',
    packages=find_packages(exclude=('data')),
    install_requires=reqs.strip().split('\n'),
)
```
