### ISSUE TITLE
OSError: [Errno 12] Cannot allocate memory

### ISSUE THREAD

**Issue by POMCP** [facebookresearch/DrQA#53]
When trying to build the TF-IDF model after the 8th Batch I get the above-mentioned error:

System Information: Data Science Virtual Machine running Linux on Azure with 56G memory and 330G Hard drive.

I am running everything from a directory mounted on /dev/sdb1

The following is the descriptive error message:

10/24/2017 03:32:38 PM: [ -------------------------Batch 7/11------------------------- ]
10/24/2017 03:36:43 PM: [ -------------------------Batch 8/11------------------------- ]
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/anaconda/envs/py35/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/anaconda/envs/py35/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/anaconda/envs/py35/lib/python3.5/multiprocessing/pool.py", line 366, in _handle_workers
    pool._maintain_pool()
  File "/anaconda/envs/py35/lib/python3.5/multiprocessing/pool.py", line 240, in _maintain_pool
    self._repopulate_pool()
  File "/anaconda/envs/py35/lib/python3.5/multiprocessing/pool.py", line 233, in _repopulate_pool
    w.start()
  File "/anaconda/envs/py35/lib/python3.5/multiprocessing/process.py", line 105, in start
    self._popen = self._Popen(self)
  File "/anaconda/envs/py35/lib/python3.5/multiprocessing/context.py", line 267, in _Popen
    return Popen(process_obj)
  File "/anaconda/envs/py35/lib/python3.5/multiprocessing/popen_fork.py", line 20, in __init__
    self._launch(process_obj)
  File "/anaconda/envs/py35/lib/python3.5/multiprocessing/popen_fork.py", line 67, in _launch
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory

There was a previous issue in the log that was closed stating that it was a windows machine. Any pointers on this one?

**Comment by ajfisch** [comment]
The TFIDF takes quite a bit of memory to build especially on a big corpus. Can you check how much RAM is being used at the time of the crash?

**Comment by POMCP** [comment]
![screen shot 2017-11-01 at 15 53 36](https://user-images.githubusercontent.com/23533095/32280661-e5b99ed4-bf1c-11e7-8c69-1bd50653afcb.png)
I think this is absolutely a memory issue. This was the footprint in run time. A parent process seems to dominate the RAM usage peaking at 96 %, this happens around batch 8 and then the program crashes. Here are some snapshots that can be of reference.
![screen shot 2017-11-01 at 15 51 03](https://user-images.githubusercontent.com/23533095/32280622-cd33ff30-bf1c-11e7-8fd2-dc3b47a4a9ad.png)

**Comment by ajfisch** [comment]
Yeah, its a memory issue. 56GB RAM isn't enough to build the tfidf index. You could try reducing the hash size.

See #32 for the same problem.
