### ISSUE TITLE
Processing issue in Document Reader

### ISSUE THREAD

**Issue by samdash** [facebookresearch/DrQA#59]
I am seeing below issue when executing below command.
 python scripts/reader/preprocess.py data/datasets data/datasets/ --split SQuAD-v1.1-dev

```
Will write to file data/datasets/SQuAD-v1.1-dev-processed-corenlp.txt
Process ForkPoolWorker-1:
Process ForkPoolWorker-3:
Process ForkPoolWorker-2:
Traceback (most recent call last):
Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/pexpect/expect.py", line 99, in expect_loop
    incoming = spawn.read_nonblocking(spawn.maxread, timeout)
  File "/anaconda3/lib/python3.6/site-packages/pexpect/pty_spawn.py", line 462, in read_nonblocking
    raise TIMEOUT('Timeout exceeded.')
  File "/anaconda3/lib/python3.6/site-packages/pexpect/expect.py", line 99, in expect_loop
    incoming = spawn.read_nonblocking(spawn.maxread, timeout)
  File "/anaconda3/lib/python3.6/site-packages/pexpect/pty_spawn.py", line 462, in read_nonblocking
    raise TIMEOUT('Timeout exceeded.')
pexpect.exceptions.TIMEOUT: Timeout exceeded.
pexpect.exceptions.TIMEOUT: Timeout exceeded.

During handling of the above exception, another exception occurred:


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/anaconda3/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/anaconda3/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/anaconda3/lib/python3.6/multiprocessing/pool.py", line 103, in worker
    initializer(*initargs)
  File "scripts/reader/preprocess.py", line 29, in init
    TOK = tokenizer_class(**options)
```

**Comment by ajfisch** [comment]
Have you verified that your tokenizer is installed properly https://github.com/facebookresearch/DrQA#installing-drqa

**Comment by samdash** [comment]
Yes i have verified that corenlp works fine.
below steps works fine
```
from drqa.tokenizers import CoreNLPTokenizer
tok = CoreNLPTokenizer()
tok.tokenize('hello world').words()

```

I am trying to preprocess my sample data in the format as described below.

```
'{"question": "q1", "answer": ["a11", ..., "a1i"]}'
'{"question": "qN", "answer": ["aN1", ..., "aNi"]}'
```

I am still getting above error, for now my sample data ( attached here) 
[sample_qa.txt](https://github.com/facebookresearch/DrQA/files/1464355/sample_qa.txt)

**Comment by samdash** [comment]
Looks to be working fine now ... thanks Adam.
