### ISSUE TITLE
Issue of Build DB

### ISSUE THREAD

**Issue by Mrlyk423** [facebookresearch/DrQA#60]
When I try to build a database for a Wikipedia corpus (11GB, ~2000W docs), I suffer from the following issue that the multiprocessing seems to not support Big number. Is there any suggestion?

11/12/2017 10:35:26 AM: [ Reading into database... ]
  0%|             Process ForkPoolWorker-1:                                                                                               | 0/1 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/linyankai/anaconda3/envs/python35/lib/python3.5/multiprocessing/pool.py", line 125, in worker
    put((job, i, result))
  File "/home/linyankai/anaconda3/envs/python35/lib/python3.5/multiprocessing/queues.py", line 355, in put
    self._writer.send_bytes(obj)
  File "/home/linyankai/anaconda3/envs/python35/lib/python3.5/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/home/linyankai/anaconda3/envs/python35/lib/python3.5/multiprocessing/connection.py", line 393, in _send_bytes
    header = struct.pack("!i", n)
struct.error: 'i' format requires -2147483648 <= number <= 2147483647

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/linyankai/anaconda3/envs/python35/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/home/linyankai/anaconda3/envs/python35/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/linyankai/anaconda3/envs/python35/lib/python3.5/multiprocessing/pool.py", line 130, in worker
    put((job, i, (False, wrapped)))
  File "/home/linyankai/anaconda3/envs/python35/lib/python3.5/multiprocessing/queues.py", line 355, in put
    self._writer.send_bytes(obj)
  File "/home/linyankai/anaconda3/envs/python35/lib/python3.5/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/home/linyankai/anaconda3/envs/python35/lib/python3.5/multiprocessing/connection.py", line 393, in _send_bytes
    header = struct.pack("!i", n)
struct.error: 'i' format requires -2147483648 <= number <= 2147483647

**Comment by Mrlyk423** [comment]
Solved by splitting files into several small files.
