### ISSUE TITLE
TIMEOUT('Timeout exceeded.')

### ISSUE THREAD

**Issue by samdash** [facebookresearch/DrQA#65]
Seeing below exception consistently, after i added more data. document retriever is however working fine and it is also working fine with smaller dataset . not sure what could be the issue. , can you please let me know, my classpath is correct, only thing i changed is below to build the DB in retriever/build_db.py

from 
`doc = json.loads(line) 
`
to
 
`doc = json.loads(line,strict=False) 
`
to ignore invalid control character error i was getting

11/30/2017 04:26:06 PM: [ Processing 1 queries... ]
11/30/2017 04:26:06 PM: [ Retrieving top 5 docs... ]
multiprocessing.pool.RemoteTraceback:
"""
```
Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/pexpect/expect.py", line 99, in expect_loop
    incoming = spawn.read_nonblocking(spawn.maxread, timeout)
  File "/anaconda3/lib/python3.6/site-packages/pexpect/pty_spawn.py", line 462, in read_nonblocking
    raise TIMEOUT('Timeout exceeded.')
pexpect.exceptions.TIMEOUT: Timeout exceeded.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/anaconda3/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/Users/samaraarkotti/Documents/MachineLearning/DrQA/drqa/pipeline/drqa.py", line 53, in tokenize_text
    return PROCESS_TOK.tokenize(text)
  File "/Users/samaraarkotti/Documents/MachineLearning/DrQA/drqa/tokenizers/corenlp_tokenizer.py", line 96, in tokenize
    self.corenlp.expect_exact('NLP>', searchwindowsize=100)
  File "/anaconda3/lib/python3.6/site-packages/pexpect/spawnbase.py", line 390, in expect_exact
    return exp.expect_loop(timeout)
  File "/anaconda3/lib/python3.6/site-packages/pexpect/expect.py", line 107, in expect_loop
    return self.timeout(e)
  File "/anaconda3/lib/python3.6/site-packages/pexpect/expect.py", line 70, in timeout
    raise TIMEOUT(msg)
pexpect.exceptions.TIMEOUT: Timeout exceeded.
<pexpect.pty_spawn.spawn object at 0x1530af79e8>
command: /bin/bash
args: ['/bin/bash']
buffer (last 100 chars): b' '
before (last 100 chars): b' '
after: <class 'pexpect.exceptions.TIMEOUT'>
match: None
match_index: None
exitstatus: None
flag_eof: False
pid: 93114
child_fd: 16
closed: False
timeout: 60
delimiter: <class 'pexpect.exceptions.EOF'>
logfile: None
logfile_read: None
logfile_send: None
maxread: 100000
ignorecase: False
searchwindowsize: None
delaybeforesend: 0
delayafterclose: 0.1
delayafterterminate: 0.1
searcher: searcher_string:
    0: "b'NLP>'"
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "scripts/pipeline/interactive.py", line 81, in process
    question, candidates, top_n, n_docs, return_context=True
  File "/Users/samaraarkotti/Documents/MachineLearning/DrQA/drqa/pipeline/drqa.py", line 184, in process
    top_n, n_docs, return_context
  File "/Users/samaraarkotti/Documents/MachineLearning/DrQA/drqa/pipeline/drqa.py", line 225, in process_batch
    s_tokens = s_tokens.get()
  File "/anaconda3/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
pexpect.exceptions.TIMEOUT: Timeout exceeded.
<pexpect.pty_spawn.spawn object at 0x1530af79e8>
command: /bin/bash
args: ['/bin/bash']
buffer (last 100 chars): b' '
before (last 100 chars): b' '
after: <class 'pexpect.exceptions.TIMEOUT'>
match: None
match_index: None
exitstatus: None
flag_eof: False
pid: 93114
child_fd: 16
closed: False
timeout: 60
delimiter: <class 'pexpect.exceptions.EOF'>
logfile: None
logfile_read: None
logfile_send: None
maxread: 100000
ignorecase: False
searchwindowsize: None
delaybeforesend: 0
delayafterclose: 0.1
delayafterterminate: 0.1
searcher: searcher_string:
    0: "b'NLP>'"
>>>
```

**Comment by kickbox** [comment]
Looks like an issue with your tockenizer. Please refer this https://github.com/facebookresearch/DrQA/issues/61
and check if you have installed coernlp properly.

**Comment by samdash** [comment]
I have installed corenlp correctly as mentioned above, it is working fine for first 2 times and from 3rd time it is throwing the error.

**Comment by ajfisch** [comment]
Probably whatever invalid control character that caused `json.loads` to fail is also causing the tokenizer to fail. You can try using the SpacyTokenizer... a bit more robust in Python and will give a more informative error

**Comment by samdash** [comment]
Thanks Adam , will do that and see.
