### ISSUE TITLE
Time out exceeded

### ISSUE THREAD

**Issue by jinfagang** [facebookresearch/DrQA#7]
This test command got error, I have already installed corenlp
```
>>> tok = CoreNLPTokenizer()
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pexpect/expect.py", line 97, in expect_loop
    incoming = spawn.read_nonblocking(spawn.maxread, timeout)
  File "/usr/lib/python3/dist-packages/pexpect/pty_spawn.py", line 452, in read_nonblocking
    raise TIMEOUT('Timeout exceeded.')
pexpect.exceptions.TIMEOUT: Timeout exceeded.

```

**Comment by jinfagang** [comment]
Well, another error;

```
>>> import drqa.tokenizers
>>> drqa.tokenizer.set_default('corenlp_classpath', '/media/jintian/Netac/CodeSpace/AISpace/pytorch_space/other_repos/DrQA/data/corenlp/*')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'drqa' has no attribute 'tokenizer'

```

**Comment by ajfisch** [comment]
I trust you have solved this? The error here is you likely did not have Corenlp in your classpath. The second error is a typo -- you need drqa.tokenizers not drqa.tokenize.

**Comment by jinfagang** [comment]
Solved all problems, thanks ajfisch, the drqa.tokenizers is right, seems README.md typo wrong should be fixed.

**Comment by ajfisch** [comment]
I see the typo in the README. Thanks for pointing it out! I will fix it.
