### ISSUE TITLE
Run inteactive.py error

### ISSUE THREAD

**Issue by jinfagang** [facebookresearch/DrQA#8]
Run this script:
```
python3 scripts/retriever/interactive.py --model data/reader/single.mdl
```
Got error:
```
➜  DrQA git:(master) python3 scripts/retriever/interactive.py --model data/reader/single.mdl 
07/30/2017 10:44:31 AM: [ Initializing ranker... ]
07/30/2017 10:44:31 AM: [ Loading data/reader/single.mdl ]
Traceback (most recent call last):
  File "scripts/retriever/interactive.py", line 27, in <module>
    ranker = retriever.get_class('tfidf')(tfidf_path=args.model)
  File "/media/jintian/Netac/CodeSpace/AISpace/pytorch_space/other_repos/DrQA/drqa/retriever/tfidf_doc_ranker.py", line 37, in __init__
    matrix, metadata = utils.load_sparse_csr(tfidf_path)
  File "/media/jintian/Netac/CodeSpace/AISpace/pytorch_space/other_repos/DrQA/drqa/retriever/utils.py", line 34, in load_sparse_csr
    matrix = sp.csr_matrix((loader['data'], loader['indices'],
TypeError: 'int' object is not subscriptable

```
Any idea?

**Comment by ajfisch** [comment]
Hi!

You are loading the reader model for an interactive *retriever* session. You need to load a retriever model -- the default is in data/wikipedia/docs-tfidf...

**Comment by ajfisch** [comment]
(Note too that if you want to just use the default, just leave out the --model argument.)

**Comment by jinfagang** [comment]
@ajfisch  Hi, thanks for your reply, I have run the download.sh script, but here is what I got:
```
.
├── corenlp
│   ├── ejml-0.23.jar
│   ├── javax.json-api-1.0-sources.jar
│   ├── javax.json.jar
│   ├── joda-time-2.9-sources.jar
│   ├── joda-time.jar
│   ├── jollyday-0.4.9-sources.jar
│   ├── jollyday.jar
│   ├── protobuf.jar
│   ├── slf4j-api.jar
│   ├── slf4j-simple.jar
│   ├── stanford-corenlp-3.8.0.jar
│   ├── stanford-corenlp-3.8.0-javadoc.jar
│   ├── stanford-corenlp-3.8.0-models.jar
│   ├── stanford-corenlp-3.8.0-sources.jar
│   ├── xom-1.2.10-src.jar
│   └── xom.jar
├── datasets
│   ├── CuratedTrec-test.txt
│   ├── CuratedTrec-train.txt
│   ├── freebase-entities.txt
│   ├── SQuAD-v1.1-dev.json
│   ├── SQuAD-v1.1-dev.txt
│   ├── SQuAD-v1.1-train.json
│   ├── SQuAD-v1.1-train.txt
│   ├── WebQuestions-test.txt
│   ├── WebQuestions-train.txt
│   ├── WikiMovies-entities.txt
│   ├── WikiMovies-test.txt
│   └── WikiMovies-train.txt
├── reader
│   ├── multitask.mdl
│   └── single.mdl
└── wikipedia
    ├── docs.db
    └── docs-tfidf-ngram=2-hash=16777216-tokenizer=simple.npz

```
