### ISSUE TITLE
 Distant Supervision (DS)，TypeError: expected string or buffer

### ISSUE THREAD

**Issue by MacXing** [facebookresearch/DrQA#82]
hi,
I am debugging Distant Supervision (DS), the data is formatA,
An error occurred:
01/16/2018 01:53:59 PM: [Searching documents ...]
multiprocessing.pool.RemoteTraceback:
"" "
Traceback (most recent call last):
   File "/home/innovate/anaconda3/lib/python3.6/multiprocessing/pool.py", line 119, in worker
     result = (True, func (* args, ** kwds))
   File "generate.py", line 169, in search_docs
     for j, paragraph in enumerate (re.split (r '\ n +', fetch_text (doc_id))):
   File "/home/innovate/anaconda3/lib/python3.6/site-packages/regex-2017.12.12-py3.6-linux-x86_64.egg/regex.py", line 319, in split
     return _compile (pattern, flags, kwargs) .split (string, maxsplit, concurrent)
TypeError: expected string or buffer
I do not know where is wrong, I want to solve, thanks

**Comment by ajfisch** [comment]
This is the same error as #77 and #81, let's keep discussion there
