### ISSUE TITLE
Error while running this line: tok.tokenize('hello world').words()

### ISSUE THREAD

**Issue by saiabhishekgv** [facebookresearch/DrQA#91]
Error while running this line: tok.tokenize('hello world').words()

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/saiabhishekgv/DrQA/drqa/tokenizers/corenlp_tokenizer.py", line 101, in tokenize
    output = json.loads(output[start:].decode('utf-8'))
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by karan78tp** [comment]
try in double qoutes
tok.tokenize("hello world").words()

**Comment by ajfisch** [comment]
Is CoreNLP working correctly when run as a jar from the command line?

**Comment by saiabhishekgv** [comment]
These two statements are running:
    from drqa.tokenizers import CoreNLPTokenizer;
     tok = CoreNLPTokenizer()

I have installed CoreNLP using ./install_corenlp.sh and then export CLASSPATH=$CLASSPATH:data/corenlp/*

**Comment by pascoej** [comment]
I also get this.

**Comment by ajfisch** [comment]
A few things:
- Make sure you are running Java 8.
- Make sure your CLASSPATH is set properly (if you are using a shell other than `bash` the * might not behave as intended).
- Make sure that the Stanford CoreNLP runs on its own (**not** the python interface DrQA provides).

```bash
java -mx2g edu.stanford.nlp.pipeline.StanfordCoreNLP
```

**Comment by RitwikGopi** [comment]
Try this. Replace tok with below line
    tok = CoreNLPTokenizer(classpath='./data/corenlp/')
`./data/corenlp/'` can be replaced with your data path. 
It worked for me let me know if it is working for you

**Comment by learningneo** [comment]
Hi,
I faced this very issue to start with. There are multiple reasons why it can happen, most of which have been covered so far. But my resolution came by using an additional argument, hence I will detail the approach covering all the points above. 

1. Java version issue: I faced java version issue - for which I downloaded jdk1.8 and set the PATH variable appropriately, so that the java related errors are resolved. Clear sign of those being resolved was java version coming out perfectly. So, resolution is - a) Download correct JDK; b) Set the PATH
 --> How to set PATH: export PATH=$PATH:/path/to/jdk1.8.0_102/bin #(version can be your preferred but 1.8+)
2. StanfordCoreNLP CLASSPATH issue: I downloaded the Stanford CoreNLP version dated 2017-06-09 (as per the install_corenlp.sh). The first issue I faced was to set CLASSPATH properly.
--> How to set CLASSPATH: export CLASSPATH=/path/to/stanford-corenlp-full-2017-06-09/*
--> How to confirm if this is working fine: fire command below:
`java -mx2g -cp "/data/indbks/common/stanford-corenlp-full-2017-06-09/*" edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit -tokenize.options untokenizable=noneDelete,invertible=true -outputFormat json -prettyPrint false`
Once the above command provides the command line, provide any text there and it should give a tokenized output such as:
`NLP> "hello world"
{"sentences":[{"index":0,"tokens":[{"index":1,"word":"\"hello","originalText":"\"hello","characterOffsetBegin":0,"characterOffsetEnd":6},{"index":2,"word":"world\"","originalText":"world\"","characterOffsetBegin":7,"characterOffsetEnd":13}]}]}`

Once you have reached till here, rest assured, everything is working fine. Now despite this, you may face issues when you invoke the Python code. The reasons are - The subprocess is either unable to start because of some issues, or you are being impatient and it will start in a minute or so! In my case, it was the latter. after I instantiated the CoreNLPTokenizer, it took almost 20 secs for the subprocess to spawn, which means that my call to tokenize method gave error till then and once the subprocess was alive and kicking, the tokenizer call also started working!

P.S. - This did not mean that the code overall is working - but I think this phenomenon is the root cause for #93 as well. If we get the code to simply "wait" for the process to start and then pass the "text" (see tokenize_text method of drqa.py), I have a feeling that the whole thing will start working. I will check how I can get to that soon.

**Comment by icegeek22** [comment]
mine worked by changing memory to '4g' from '2g'.

**Comment by fpcsong** [comment]
we can see at file ```drqa/tokenizers/corenlp_tokenizer.py line 98-103```, **output** is a string contains a json-like substring, but not startwith```{sentences``` but startwith ```{\r\n sentences```, after update this line to ```start = output.find(b'{\r\n  "sentences":')```, it works for me.

**Comment by krutikabapat** [comment]
I was able to solve this problem by changing the tokenizer from CoreNLP to spacy.
To use it, go to ```drqa/pipeline/__init__.py``` and change the DEFAULT list to below:
```DEFAULTS = { 'tokenizer': SpacyTokenizer, 'ranker': TfidfDocRanker, 'db': DocDB, 'reader_model': os.path.join(DATA_DIR, 'reader/multitask.mdl'), }```
