### ISSUE TITLE
error  in process('What is question answering?') JSON DECODE ERROR

### ISSUE THREAD

**Issue by karan78tp** [facebookresearch/DrQA#93]

**Comment by ajfisch** [comment]
Can you give more context, like the output and full error? Does the tokenizer work independently?

**Comment by karan78tp** [comment]
Interactive DrQA
>> process(question, candidates=None, top_n=1, n_docs=5)
>> usage()

>>> process('What is question answering?')
02/17/2018 06:53:21 AM: [ Processing 1 queries... ]
02/17/2018 06:53:21 AM: [ Retrieving top 5 docs... ]
multiprocessing.pool.RemoteTraceback: 


The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/lib/python3.5/code.py", line 91, in runcode
    exec(code, self.locals)
  File "<console>", line 1, in <module>
  File "scripts/pipeline/interactive.py", line 84, in process
    question, candidates, top_n, n_docs, return_context=True
  File "/home/krank/DrQA/drqa/pipeline/drqa.py", line 184, in process
    top_n, n_docs, return_context
  File "/home/krank/DrQA/drqa/pipeline/drqa.py", line 224, in process_batch
    q_tokens = q_tokens.get()
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 608, in get
    raise self._value
json.decoder.JSONDecodeError: Expecting value: line 2 column 1 (char 1)

**Comment by dusk256** [comment]
It is an issue of CoreNLPTokenizer, same error when try to check out if it works:
```
from drqa.tokenizers import CoreNLPTokenizer
tok = CoreNLPTokenizer()
tok.tokenize('hello world').words()  # Should complete immediately
```
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/name/DrQA/drqa/tokenizers/corenlp_tokenizer.py", line 101, in tokenize
    output = json.loads(output[start:].decode('utf-8'))
  File "/home/name/anaconda3/envs/drqa/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/home/name/anaconda3/envs/drqa/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/name/anaconda3/envs/drqa/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 2 column 1 (char 1)
```

**Comment by ajfisch** [comment]
Can you confirm that you have the correct corenlp download and java version, by following suggestions on #91 ?

**Comment by dusk256** [comment]
Yes, java version is 1.8.0_151. CoreNLP is from the ./install_corenlp.sh script. 
CoreNLP runs on it's own, but in my case just when I'm adding flag  -Xmx4096m to use more space.
``java -mx2g -Xmx4096m edu.stanford.nlp.pipeline.StanfordCoreNLP

**Comment by mooreniemi** [comment]
I found `java -mx4g edu.stanford.nlp.pipeline.StanfordCoreNLP` worked for me, but `python scripts/pipeline/interactive.py` still fails:

```
>>> process('who is tesla?')
02/27/2018 11:52:12 AM: [ Processing 1 queries... ]
02/27/2018 11:52:12 AM: [ Retrieving top 5 docs... ]
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/Users/amooren/Code/DrQA/drqa/pipeline/drqa.py", line 53, in tokenize_text
    return PROCESS_TOK.tokenize(text)
  File "/Users/amooren/Code/DrQA/drqa/tokenizers/corenlp_tokenizer.py", line 101, in tokenize
    output = json.loads(output[start:].decode('utf-8'))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 2 column 1 (char 1)
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "scripts/pipeline/interactive.py", line 81, in process
    question, candidates, top_n, n_docs, return_context=True
  File "/Users/amooren/Code/DrQA/drqa/pipeline/drqa.py", line 184, in process
    top_n, n_docs, return_context
  File "/Users/amooren/Code/DrQA/drqa/pipeline/drqa.py", line 224, in process_batch
    q_tokens = q_tokens.get()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
json.decoder.JSONDecodeError: Expecting value: line 2 column 1 (char 1)
```

**Comment by ajfisch** [comment]
The default is still 2g in the python interface. So try changing [this line](https://github.com/facebookresearch/DrQA/blob/master/drqa/tokenizers/corenlp_tokenizer.py#L32) to 4g.

**Comment by mooreniemi** [comment]
Hmm, did your edit and no difference. I can see via grepping processes that 4 corenlp processes were launched:

```
77410 ttys007    0:00.81 /usr/bin/java -mx4g -cp :data/corenlp/* edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit -tokenize.options untokenizable=noneDelete,invertible=true -outputFormat json -prettyPrint false
```

And if I just try to use this myself:

```
/usr/bin/java -mx4g -cp :data/corenlp/* edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit -tokenize.options untokenizable=noneDelete,invertible=true -outputFormat json -prettyPrint false
[main] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator tokenize
[main] INFO edu.stanford.nlp.pipeline.TokenizerAnnotator - No tokenizer type provided. Defaulting to PTBTokenizer.
[main] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator ssplit

Entering interactive shell. Type q RETURN or EOF to quit.
NLP> who is tesla
{"sentences":[{"index":0,"tokens":[{"index":1,"word":"who","originalText":"who","characterOffsetBegin":0,"characterOffsetEnd":3,"before":"","after":" "},{"index":2,"word":"is","originalText":"is","characterOffsetBegin":4,"characterOffsetEnd":6,"before":" ","after":" "},{"index":3,"word":"tesla","originalText":"tesla","characterOffsetBegin":7,"characterOffsetEnd":12,"before":" ","after":""}]}]}
NLP>
```

**Comment by ajfisch** [comment]
Hm. Well it might be too heavy a load for your machine (since it's launching 4 concurrent tokenizers, each with 4g reserved -- might be running out of heap space). Let's try to debug step by step...

- Java command line works. Good.
- Can you try now accessing the python interface?
```python
>>> from drqa.tokenizers import CoreNLPTokenizer
>>> tok = CoreNLPTokenizer(mem='4g')
>>> tok.tokenize('hello').words()
['hello']
```
- Can you try launching the interactive with `num_workers=1` as input to the `pipeline.DrQA` object (line 64)?

**Comment by mooreniemi** [comment]
Just going to retrace my steps for subsequent folks, skip to bottom for my results.

Trying directly in a `python` shell:

```
Python 3.6.4 (v3.6.4:d48ecebad5, Dec 18 2017, 21:07:28)
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from drqa.tokenizers import CoreNLPTokenizer
>>> tok = CoreNLPTokenizer(mem='4g')
>>> tok.tokenize('hello').words()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/amooren/Code/DrQA/drqa/tokenizers/corenlp_tokenizer.py", line 101, in tokenize
    output = json.loads(output[start:].decode('utf-8'))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 2 column 1 (char 1)
>>>
```

When I added `print` lines I saw:

```
output: b'ring interactive shell. Type q RETURN or EOF to quit.\r\n'
start: -1
```

I checked that the process was launched, returned to the Python prompt, and I guess it'd finished loading, because then it worked:

```
>>> tok.tokenize('hello').words()
output: b' {"sentences":[{"index":0,"tokens":[{"index":1,"word":"hello","originalText":"hello","characterOffsetBegin":0,"characterOffsetEnd":5,"before":"","after":""}]}]}\r\n'
start: 1
['hello']
```

So as a general note, "wait a little bit" before executing `tok.tokenize('hello').words()`. (Maybe the interactive script should block until the load is confirmed?)  That made me hope it was just an issue of waiting in the `pipeline/interactive` script. I gave it 10 seconds and retried several times, but this was my output.

```
>>> process('who is tesla?')
02/27/2018 01:37:13 PM: [ Processing 1 queries... ]
02/27/2018 01:37:13 PM: [ Retrieving top 5 docs... ]
output: b'ore":" ","after":""},{"index":32,"word":".","originalText":".","characterOffsetBegin":376,"characterOffsetEnd":377,"before":"","after":" "}]},{"index":3,"tokens":[{"index":1,"word":"Eventually","originalText":"Eventually","characterOffsetBegin":378,"characterOffsetEnd":388,"before":" ","after":""},{"index":2,"word":",","originalText":",","characterOffsetBegin":388,"characterOffsetEnd":389,"before":"","after":" "},{"index":3,"word":"all","originalText":"all","characterOffsetBegin":390,"characterOffsetEnd":393,"before":" ","after":" "},{"index":4,"word":"Tesla","originalText":"Tesla","characterOffsetBegin":394,"characterOffsetEnd":399,"before":" ",'
start: -1
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/Users/amooren/Code/DrQA/drqa/pipeline/drqa.py", line 53, in tokenize_text
    return PROCESS_TOK.tokenize(text)
  File "/Users/amooren/Code/DrQA/drqa/tokenizers/corenlp_tokenizer.py", line 103, in tokenize
    output = json.loads(output[start:].decode('utf-8'))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "scripts/pipeline/interactive.py", line 82, in process
    question, candidates, top_n, n_docs, return_context=True
  File "/Users/amooren/Code/DrQA/drqa/pipeline/drqa.py", line 184, in process
    top_n, n_docs, return_context
  File "/Users/amooren/Code/DrQA/drqa/pipeline/drqa.py", line 224, in process_batch
    q_tokens = q_tokens.get()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
output: b'er":" "},{"index":5,"word":"stations","originalText":"stations","characterOf>>> fsetBegin":400,"characterOffsetEnd":408,"before":" ","after":" "},{"index":6,"word":"will","originalText":"will","characterOffsetBegin":409,"characterOffsetEnd":413,"before":" ","after":" "},{"index":7,"word":"be","originalText":"be","characterOffsetBegin":414,"characterOffsetEnd":416,"before":" ","after":" "},{"index":8,"word":"assisted","originalText":"assisted","characterOffsetBegin":417,"characterOffsetEnd":425,"before":" ","after":" "},{"index":9,"word":"by","originalText":"by","characterOffsetBegin":426,"characterOffsetEnd":428,"before":" ","after":" "},{"index":10,"word":"solar","originalText":"solar","characterOffsetBegin":429,"characterOffsetEnd":434,"before":" ","after":" "},{"index":11,"word":"power","originalText":"power","characterOffsetBegin":435,"characterOffsetEnd":440,"before":" ","after":""},{"index":12,"word":".","originalText":".","characterOffsetBegin":440,"characterOffsetEnd":441,"before":"","after":""}]}]}\r\n'
start: -1
```

**Comment by soumyaw** [comment]
What is the solution to this? I am unable to execute the interactive.py scripts since I keep getting the json.decoder.JSONDecodeError too.

**Comment by ThomasWXW** [comment]
One possible solution is to change python 3.6 to python 3.5. I am getting the json.decoder.JSONDecodeError at line 224 of drqa.py when using python3.6. And everything is fine when using python3.5. The probability is that there are some incompatible changes in multiprocessing between python3.5 and python3.6.

**Comment by ThomasWXW** [comment]
I just found that the "json.decoder.JSONDecodeError" happens at the line 101 in corenlp_tokenizer.py.
start = output.find(b'{"sentences":') gives -1 in 'start'. Because the value output is something like "b'ring interactive shell. Type q RETURN or EOF to quit.\r\n'".

**Comment by amitakamath** [comment]
I followed the instructions for downloading the datasets and CoreNLP, and I'm getting the right output for `tok.tokenize('hello').words()`, but I'm getting a similar JSON Decode error as previous posters upon running `python scripts/reader/preprocess.py data/datasets data/datasets --split SQuAD-v1.1-train` :

```
Loading dataset data/datasets/SQuAD-v1.1-train.json
Will write to file data/datasets/SQuAD-v1.1-train-processed-corenlp.txt
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "scripts/reader/preprocess.py", line 36, in tokenize
    tokens = TOK.tokenize(text)
  File "/home/amita/Desktop/NLP/Project/DrQA/drqa/tokenizers/corenlp_tokenizer.py", line 102, in tokenize
    output = json.loads(output[start:].decode('utf-8'))
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 2 column 1 (char 1)
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "scripts/reader/preprocess.py", line 150, in <module>
    for ex in process_dataset(dataset, args.tokenizer, args.workers):
  File "scripts/reader/preprocess.py", line 85, in process_dataset
    q_tokens = workers.map(tokenize, data['questions'])
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 260, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 608, in get
    raise self._value
json.decoder.JSONDecodeError: Expecting value: line 2 column 1 (char 1)

``` 

Could you please let me know how I could resolve this? I'm trying to preprocess SQuAD in order to train DrQA on it.

**Comment by ThomasWXW** [comment]
I think there should be a version problem in CoreNLP or a bug in corenlp_tokenizer.py. We are still waiting for an update. For the moment, I suggest that you can use spacy tokenizer to train, which works fine for me.  @amitakamath

**Comment by ajfisch** [comment]
What version of CoreNLP are you using? Later versions (past the one in the download script) load extra files for TokensRegexNERAnnotator which take a bit of time and might be causing the timeouts/truncation... I am not sure.

Without being able to replicate the errors myself, it is hard for me to propose a solution. In the meantime I suggest using the Spacy tokenizer option instead.

**Comment by learningneo** [comment]
Hi guys,
As both @ThomasWXW and @ajfisch mentioned, I was successful and running the setup using SpacyTokenizer. To use it, once way can be to go to drqa/pipeline/__init__.py and change the DEFAULT list to below:
`DEFAULTS = {
    'tokenizer': SpacyTokenizer,
    'ranker': TfidfDocRanker,
    'db': DocDB,
    'reader_model': os.path.join(DATA_DIR, 'reader/multitask.mdl'),
}`

Rest should work properly.

**Comment by p-baleine** [comment]
This issue could be solved by downgrading pyexpect version from `4.4.0` to `4.3.1` in my case.

I suspect that pexpect had changed its some behavior since 4.4.

**Comment by ajfisch** [comment]
That's a good suggestion. I am using version `4.2.1`.

**Comment by dusk256** [comment]
@p-baleine Thank you! That worked

**Comment by Shuailong** [comment]
4.3.1 works! @p-baleine  thanks!

**Comment by zgp1990** [comment]
Thanks to @p-baleine   ~
this issue confused me for a long time

**Comment by seanexplode** [comment]
@p-baleine Thank you! Downgrading pexpect to 4.2.1 worked!

**Comment by dimitryslavin** [comment]
I was able to solve this problem by changing line 100 in corenlp_tokenizer.py: 

replace the following:
`start = output.find(b'{"sentences":')`

with:
`start = output.find(b'{\r\n  "sentences":') `

**Comment by krutikabapat** [comment]
I was able to solve this problem by changing the tokenizer from CoreNLP to spacy. 
To use it,  go to ```drqa/pipeline/__init__.py ``` and change the DEFAULT list to below:
```DEFAULTS = { 'tokenizer': SpacyTokenizer, 'ranker': TfidfDocRanker, 'db': DocDB, 'reader_model': os.path.join(DATA_DIR, 'reader/multitask.mdl'), }```

**Comment by Martin36** [comment]
> I was able to solve this problem by changing the tokenizer from CoreNLP to spacy.
> To use it, go to `drqa/pipeline/__init__.py ` and change the DEFAULT list to below:
> `DEFAULTS = { 'tokenizer': SpacyTokenizer, 'ranker': TfidfDocRanker, 'db': DocDB, 'reader_model': os.path.join(DATA_DIR, 'reader/multitask.mdl'), }`

This can also be done by specifying the `--tokenizer` parameter as spacy, e.g. `python scripts/pipeline/interactive.py --tokenizer spacy`. Just make sure that you have spacy v2.1.0 installed and the en_core_web_sm package downloaded.

**Comment by LT156** [comment]
KnowledgeRetrieval>DrQA>drqa>tokenizers>corenlp_tokenizer.py

I print the output,like this:

output______: b' {
\r\n  "sentences": [
\r\n   {
\r\n      "index": 0,
\r\n      "tokens": [
\r\n        {
\r\n          "index": 1,
\r\n          "word": "hello",
\r\n          "originalText": "hello",
\r\n          "characterOffsetBegin": 0,
\r\n          "characterOffsetEnd": 5,
\r\n          "before": "",
\r\n          "after": " "
\r\n        },
\r\n        {
\r\n          "index": 2,
\r\n          "word": "world",
\r\n          "originalText": "world",
\r\n          "characterOffsetBegin": 6,
\r\n          "characterOffsetEnd": 11,
\r\n          "before": " ",
\r\n          "after": ""
\r\n        }
\r\n      ]
\r\n    }
\r\n  ]
\r\n}
\r\n'

so I solve this problem through the following changes,according to dimitryslavin's work.
before: start = output.find(b' {"sentences":') 
after : start = output.find(b' {\r\n  "sentences":')
